//go:build ignore

// Command generate_stdlibgo_files regenerates files.gen.go, embedding the Go
// runtime support package as a path-keyed string map. Run via
// `go generate ./stdlibgo` from the compiler module root.
package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	paths := []string{}
	for _, dir := range []string{"runtime"} {
		matches, err := filepath.Glob(filepath.Join("..", dir, "*.go"))
		if err != nil {
			panic(err)
		}
		for _, path := range matches {
			base := filepath.Base(path)
			if strings.HasSuffix(base, "_test.go") || base == "generate.go" {
				continue
			}
			paths = append(paths, filepath.ToSlash(filepath.Join(dir, base)))
		}
	}
	sort.Strings(paths)

	var out strings.Builder
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	out.WriteString("package stdlibgo\n\n")
	out.WriteString("// Files is the embedded Go runtime support package, keyed by\n")
	out.WriteString("// slash-separated compiler-module-relative path.\n")
	out.WriteString("var Files = map[string]string{\n")
	for _, rel := range paths {
		data, err := os.ReadFile(filepath.Join("..", filepath.FromSlash(rel)))
		if err != nil {
			panic(err)
		}
		fmt.Fprintf(&out, "\t%q: %s,\n", rel, strconv.Quote(string(data)))
	}
	out.WriteString("}\n")

	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("files.gen.go", formatted, 0o644); err != nil {
		panic(err)
	}
}

//go:generate go run generate_stdlibgo_files.go
