// Package stdlibgo embeds the Go support tree needed by generated Ard programs.
//
// The embedded files live in files.gen.go (generated by
// generate_stdlibgo_files.go). MaterializedDir writes them to a content-hashed
// cache directory so go/packages can load the bundled packages regardless of the
// build's working directory.
package stdlibgo

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"sync"
)

// cacheFormat is bumped when the on-disk cache layout changes, so older caches
// are not trusted even if their content hash collides with the new scheme.
const cacheFormat = "v1"

const markerName = ".stdlibgo-ready"

// IsBundledImportPath reports whether importPath is an embedded Go package that
// must be resolved against the materialized module rather than the build's
// working directory.
func IsBundledImportPath(importPath string) bool {
	return importPath == "github.com/akonwi/ard/runtime"
}

var (
	materializeOnce sync.Once
	materializedDir string
	materializeErr  error
)

// MaterializedDir writes the embedded Go support tree to a versioned cache
// directory and returns its path. It is idempotent and safe under concurrency:
// goroutines share a sync.Once, and concurrent processes coordinate through an
// atomic directory rename plus a marker file.
func MaterializedDir() (string, error) {
	materializeOnce.Do(func() {
		materializedDir, materializeErr = materialize()
	})
	return materializedDir, materializeErr
}

// ContentHash is a stable digest of every embedded file's path and contents. It
// keys the cache directory and lets callers extend their own cache keys so a
// regenerated embed invalidates derived state.
func ContentHash() string {
	keys := make([]string, 0, len(Files))
	for k := range Files {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	h := sha256.New()
	for _, k := range keys {
		fmt.Fprintf(h, "%s\x00%d\x00", k, len(Files[k]))
		h.Write([]byte(Files[k]))
	}
	return hex.EncodeToString(h.Sum(nil))[:32]
}

func materialize() (string, error) {
	hash := ContentHash()
	base, err := os.UserCacheDir()
	if err != nil || base == "" {
		base = os.TempDir()
	}
	dir := filepath.Join(base, "ard", "stdlibgo-"+cacheFormat+"-"+hash)
	if markerMatches(dir, hash) {
		return dir, nil
	}

	parent := filepath.Dir(dir)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return "", err
	}
	// Materialize into a sibling temp dir (same filesystem) so the final move is
	// an atomic rename.
	tmp, err := os.MkdirTemp(parent, "stdlibgo-tmp-*")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(tmp)

	if err := writeFiles(tmp); err != nil {
		return "", err
	}
	// The marker is written last and is what readers validate, so a visible cache
	// dir always has complete contents.
	if err := os.WriteFile(filepath.Join(tmp, markerName), []byte(hash), 0o644); err != nil {
		return "", err
	}

	if err := os.Rename(tmp, dir); err != nil {
		// Lost the race (or the destination otherwise exists): trust it only if a
		// concurrent writer left a matching marker.
		if markerMatches(dir, hash) {
			return dir, nil
		}
		return "", err
	}
	return dir, nil
}

func markerMatches(dir, hash string) bool {
	data, err := os.ReadFile(filepath.Join(dir, markerName))
	return err == nil && string(data) == hash
}

func writeFiles(dir string) error {
	for rel, content := range Files {
		path := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}
