// Code generated by generate.go; DO NOT EDIT.

package vm

import (
	"fmt"

	"github.com/akonwi/ard/ffi"
)

// RegisterGeneratedFFIFunctions registers all discovered FFI functions
func (r *RuntimeFFIRegistry) RegisterGeneratedFFIFunctions() error {
	if err := r.Register("JsonEncode", ffi.JsonEncode); err != nil {
		return fmt.Errorf("failed to register JsonEncode: %w", err)
	}
	if err := r.Register("FloatFromStr", ffi.FloatFromStr); err != nil {
		return fmt.Errorf("failed to register FloatFromStr: %w", err)
	}
	if err := r.Register("FloatFromInt", ffi.FloatFromInt); err != nil {
		return fmt.Errorf("failed to register FloatFromInt: %w", err)
	}
	if err := r.Register("FloatFloor", ffi.FloatFloor); err != nil {
		return fmt.Errorf("failed to register FloatFloor: %w", err)
	}
	if err := r.Register("IntFromStr", ffi.IntFromStr); err != nil {
		return fmt.Errorf("failed to register IntFromStr: %w", err)
	}
	if err := r.Register("NewList", ffi.NewList); err != nil {
		return fmt.Errorf("failed to register NewList: %w", err)
	}
	if err := r.Register("Print", ffi.Print); err != nil {
		return fmt.Errorf("failed to register Print: %w", err)
	}
	if err := r.Register("ReadLine", ffi.ReadLine); err != nil {
		return fmt.Errorf("failed to register ReadLine: %w", err)
	}
	if err := r.Register("PanicWithMessage", ffi.PanicWithMessage); err != nil {
		return fmt.Errorf("failed to register PanicWithMessage: %w", err)
	}
	if err := r.Register("EnvGet", ffi.EnvGet); err != nil {
		return fmt.Errorf("failed to register EnvGet: %w", err)
	}
	if err := r.Register("GetTodayString", ffi.GetTodayString); err != nil {
		return fmt.Errorf("failed to register GetTodayString: %w", err)
	}
	if err := r.Register("SqliteCreateConnection", ffi.SqliteCreateConnection); err != nil {
		return fmt.Errorf("failed to register SqliteCreateConnection: %w", err)
	}
	if err := r.Register("SqliteClose", ffi.SqliteClose); err != nil {
		return fmt.Errorf("failed to register SqliteClose: %w", err)
	}
	if err := r.Register("SqliteExec", ffi.SqliteExec); err != nil {
		return fmt.Errorf("failed to register SqliteExec: %w", err)
	}
	if err := r.Register("SqliteQuery", ffi.SqliteQuery); err != nil {
		return fmt.Errorf("failed to register SqliteQuery: %w", err)
	}
	if err := r.Register("SqliteFirst", ffi.SqliteFirst); err != nil {
		return fmt.Errorf("failed to register SqliteFirst: %w", err)
	}
	if err := r.Register("SqliteInsert", ffi.SqliteInsert); err != nil {
		return fmt.Errorf("failed to register SqliteInsert: %w", err)
	}
	if err := r.Register("SqliteUpdate", ffi.SqliteUpdate); err != nil {
		return fmt.Errorf("failed to register SqliteUpdate: %w", err)
	}
	if err := r.Register("SqliteDelete", ffi.SqliteDelete); err != nil {
		return fmt.Errorf("failed to register SqliteDelete: %w", err)
	}
	if err := r.Register("SqliteCount", ffi.SqliteCount); err != nil {
		return fmt.Errorf("failed to register SqliteCount: %w", err)
	}

	return nil
}
