// Code generated by generate.go; DO NOT EDIT.

package vm

import (
	"fmt"
	
	"github.com/akonwi/ard/ffi"
)

// RegisterGeneratedFFIFunctions registers all discovered FFI functions
func (r *RuntimeFFIRegistry) RegisterGeneratedFFIFunctions() error {
	if err := r.Register("json.encode", ffi.Encode); err != nil {
		return fmt.Errorf("failed to register json.encode: %w", err)
	}
	if err := r.Register("runtime.print", ffi.Print); err != nil {
		return fmt.Errorf("failed to register runtime.print: %w", err)
	}
	if err := r.Register("runtime.read_line", ffi.ReadLine); err != nil {
		return fmt.Errorf("failed to register runtime.read_line: %w", err)
	}
	if err := r.Register("runtime.panic_with_message", ffi.PanicWithMessage); err != nil {
		return fmt.Errorf("failed to register runtime.panic_with_message: %w", err)
	}
	if err := r.Register("runtime.env_get", ffi.EnvGet); err != nil {
		return fmt.Errorf("failed to register runtime.env_get: %w", err)
	}

	return nil
}
