// Code generated by ard; DO NOT EDIT.

package ffi

import ardruntime "github.com/akonwi/ard/runtime"

type Maybe[T any] = ardruntime.Maybe[T]

func Some[T any](value T) Maybe[T] {
	return ardruntime.Some(value)
}

func None[T any]() Maybe[T] {
	return ardruntime.None[T]()
}

type Result[T, E any] = ardruntime.Result[T, E]

func Ok[T, E any](value T) Result[T, E] {
	return ardruntime.Ok[T, E](value)
}

func Err[T, E any](err E) Result[T, E] {
	return ardruntime.Err[T](err)
}

type Db = any

type RawRequest = any

type RawResponse = any

type Tx = any

type WaitGroup = any

type Conn = any

type Decoder = any

type HandlerFn = func(Request, *Response) (struct{}, error)

type JsonInput = any

type PathSegment = any

type Primitive = any

type Value = any

type Method int

type Argv struct {
	Program   string
	Arguments []string
}

type Database struct {
	Db   Db
	Path string
}

type DirEntry struct {
	Name   string
	IsFile bool
}

type Error struct {
	Expected string
	Found    string
	Path     []string
}

type Fiber[T any] struct {
	Wg     WaitGroup
	Result T
}

type IntPartition struct {
	Selected []int
	Others   []int
}

type Partition[T any] struct {
	Selected []T
	Others   []T
}

type PersonJSONTest struct {
	Name     string
	Age      int
	Employed Maybe[bool]
}

type PredictionJSONTest struct {
	Advice Maybe[string]
	Winner Maybe[WinnerJSONTest]
}

type PreparedQuery struct {
	String string
	Values []any
}

type Query struct {
	Conn   any
	String string
	Params []string
}

type Request struct {
	Method  Method
	Url     string
	Headers map[string]string
	Body    Maybe[any]
	Timeout Maybe[int]
	Raw     Maybe[RawRequest]
}

type Response struct {
	Status  int
	Headers map[string]string
	Body    string
}

type Transaction struct {
	Tx Tx
}

type WinnerJSONTest struct {
	Id      int
	Name    string
	Comment string
}

type Host struct {
	AsyncStart           func(do func() (struct{}, error)) Fiber[struct{}]
	Base64Decode         func(input string, no_pad Maybe[bool]) (string, error)
	Base64DecodeURL      func(input string, no_pad Maybe[bool]) (string, error)
	Base64Encode         func(input string, no_pad Maybe[bool]) string
	Base64EncodeURL      func(input string, no_pad Maybe[bool]) string
	BoolToDynamic        func(val bool) any
	CryptoHashPassword   func(password string, cost Maybe[int]) (string, error)
	CryptoMd5            func(input string) string
	CryptoScryptHash     func(password string, salt_hex Maybe[string], n Maybe[int], r Maybe[int], p Maybe[int], dk_len Maybe[int]) (string, error)
	CryptoScryptVerify   func(password string, hash string, n Maybe[int], r Maybe[int], p Maybe[int], dk_len Maybe[int]) (bool, error)
	CryptoSha256         func(input string) string
	CryptoSha512         func(input string) string
	CryptoUUID           func() string
	CryptoVerifyPassword func(password string, hashed string) (bool, error)
	DecodeBool           func(data any) Result[bool, Error]
	DecodeFloat          func(data any) Result[float64, Error]
	DecodeInt            func(data any) Result[int, Error]
	DecodeString         func(data any) Result[string, Error]
	DynamicToList        func(data any) ([]any, error)
	DynamicToMap         func(data any) (map[string]any, error)
	EnvGet               func(key string) Maybe[string]
	ExtractField         func(data any, name string) (any, error)
	FSAbs                func(path string) (string, error)
	FSAppendFile         func(path string, content string) error
	FSCopy               func(from string, to string) error
	FSCreateDir          func(path string) error
	FSCreateFile         func(path string) (bool, error)
	FSCwd                func() (string, error)
	FSDeleteDir          func(path string) error
	FSDeleteFile         func(path string) error
	FSExists             func(path string) bool
	FSIsDir              func(path string) bool
	FSIsFile             func(path string) bool
	FSListDir            func(path string) (map[string]bool, error)
	FSReadFile           func(path string) (string, error)
	FSRename             func(from string, to string) error
	FSWriteFile          func(path string, content string) error
	FloatFloor           func(float float64) float64
	FloatFromInt         func(int int) float64
	FloatFromStr         func(string string) Maybe[float64]
	FloatToDynamic       func(val float64) any
	GetPathValue         func(req RawRequest, name string) string
	GetQueryParam        func(req RawRequest, name string) string
	GetReqPath           func(req RawRequest) string
	GetTodayString       func() string
	HTTPDo               func(method string, url string, body any, headers map[string]string, timeout Maybe[int]) (RawResponse, error)
	HTTPResponseBody     func(resp RawResponse) (string, error)
	HTTPResponseClose    func(resp RawResponse)
	HTTPResponseHeaders  func(resp RawResponse) map[string]string
	HTTPResponseStatus   func(resp RawResponse) int
	HTTPServe            func(port int, handlers map[string]func(Request, *Response) (struct{}, error)) error
	HexDecode            func(input string) (string, error)
	HexEncode            func(bytes string) string
	IntFromStr           func(str string) Maybe[int]
	IntToDynamic         func(val int) any
	IsNil                func(data any) bool
	JsonEncode           func(value any) (string, error)
	JsonToDynamic        func(json string) (any, error)
	ListToDynamic        func(list []any) any
	MapToDynamic         func(from map[string]any) any
	Now                  func() int
	OsArgs               func() []string
	Print                func(string string)
	ReadLine             func() (string, error)
	Sleep                func(ms int)
	SqlBeginTx           func(db Db) (Tx, error)
	SqlClose             func(db Db) error
	SqlCommit            func(tx Tx) error
	SqlCreateConnection  func(connection_string string) (Db, error)
	SqlExecute           func(conn any, sql string, values []any) error
	SqlExtractParams     func(sql string) []string
	SqlQuery             func(conn any, sql string, values []any) ([]any, error)
	SqlRollback          func(tx Tx) error
	StrToDynamic         func(val string) any
	VoidToDynamic        func() any
	WaitFor              func(wg WaitGroup)
}

func (h Host) Functions() map[string]any {
	functions := map[string]any{}
	if h.AsyncStart != nil {
		functions["AsyncStart"] = h.AsyncStart
	}
	if h.Base64Decode != nil {
		functions["Base64Decode"] = h.Base64Decode
	}
	if h.Base64DecodeURL != nil {
		functions["Base64DecodeURL"] = h.Base64DecodeURL
	}
	if h.Base64Encode != nil {
		functions["Base64Encode"] = h.Base64Encode
	}
	if h.Base64EncodeURL != nil {
		functions["Base64EncodeURL"] = h.Base64EncodeURL
	}
	if h.BoolToDynamic != nil {
		functions["BoolToDynamic"] = h.BoolToDynamic
	}
	if h.CryptoHashPassword != nil {
		functions["CryptoHashPassword"] = h.CryptoHashPassword
	}
	if h.CryptoMd5 != nil {
		functions["CryptoMd5"] = h.CryptoMd5
	}
	if h.CryptoScryptHash != nil {
		functions["CryptoScryptHash"] = h.CryptoScryptHash
	}
	if h.CryptoScryptVerify != nil {
		functions["CryptoScryptVerify"] = h.CryptoScryptVerify
	}
	if h.CryptoSha256 != nil {
		functions["CryptoSha256"] = h.CryptoSha256
	}
	if h.CryptoSha512 != nil {
		functions["CryptoSha512"] = h.CryptoSha512
	}
	if h.CryptoUUID != nil {
		functions["CryptoUUID"] = h.CryptoUUID
	}
	if h.CryptoVerifyPassword != nil {
		functions["CryptoVerifyPassword"] = h.CryptoVerifyPassword
	}
	if h.DecodeBool != nil {
		functions["DecodeBool"] = h.DecodeBool
	}
	if h.DecodeFloat != nil {
		functions["DecodeFloat"] = h.DecodeFloat
	}
	if h.DecodeInt != nil {
		functions["DecodeInt"] = h.DecodeInt
	}
	if h.DecodeString != nil {
		functions["DecodeString"] = h.DecodeString
	}
	if h.DynamicToList != nil {
		functions["DynamicToList"] = h.DynamicToList
	}
	if h.DynamicToMap != nil {
		functions["DynamicToMap"] = h.DynamicToMap
	}
	if h.EnvGet != nil {
		functions["EnvGet"] = h.EnvGet
	}
	if h.ExtractField != nil {
		functions["ExtractField"] = h.ExtractField
	}
	if h.FSAbs != nil {
		functions["FS_Abs"] = h.FSAbs
	}
	if h.FSAppendFile != nil {
		functions["FS_AppendFile"] = h.FSAppendFile
	}
	if h.FSCopy != nil {
		functions["FS_Copy"] = h.FSCopy
	}
	if h.FSCreateDir != nil {
		functions["FS_CreateDir"] = h.FSCreateDir
	}
	if h.FSCreateFile != nil {
		functions["FS_CreateFile"] = h.FSCreateFile
	}
	if h.FSCwd != nil {
		functions["FS_Cwd"] = h.FSCwd
	}
	if h.FSDeleteDir != nil {
		functions["FS_DeleteDir"] = h.FSDeleteDir
	}
	if h.FSDeleteFile != nil {
		functions["FS_DeleteFile"] = h.FSDeleteFile
	}
	if h.FSExists != nil {
		functions["FS_Exists"] = h.FSExists
	}
	if h.FSIsDir != nil {
		functions["FS_IsDir"] = h.FSIsDir
	}
	if h.FSIsFile != nil {
		functions["FS_IsFile"] = h.FSIsFile
	}
	if h.FSListDir != nil {
		functions["FS_ListDir"] = h.FSListDir
	}
	if h.FSReadFile != nil {
		functions["FS_ReadFile"] = h.FSReadFile
	}
	if h.FSRename != nil {
		functions["FS_Rename"] = h.FSRename
	}
	if h.FSWriteFile != nil {
		functions["FS_WriteFile"] = h.FSWriteFile
	}
	if h.FloatFloor != nil {
		functions["FloatFloor"] = h.FloatFloor
	}
	if h.FloatFromInt != nil {
		functions["FloatFromInt"] = h.FloatFromInt
	}
	if h.FloatFromStr != nil {
		functions["FloatFromStr"] = h.FloatFromStr
	}
	if h.FloatToDynamic != nil {
		functions["FloatToDynamic"] = h.FloatToDynamic
	}
	if h.GetPathValue != nil {
		functions["GetPathValue"] = h.GetPathValue
	}
	if h.GetQueryParam != nil {
		functions["GetQueryParam"] = h.GetQueryParam
	}
	if h.GetReqPath != nil {
		functions["GetReqPath"] = h.GetReqPath
	}
	if h.GetTodayString != nil {
		functions["GetTodayString"] = h.GetTodayString
	}
	if h.HTTPDo != nil {
		functions["HTTP_Do"] = h.HTTPDo
	}
	if h.HTTPResponseBody != nil {
		functions["HTTP_ResponseBody"] = h.HTTPResponseBody
	}
	if h.HTTPResponseClose != nil {
		functions["HTTP_ResponseClose"] = h.HTTPResponseClose
	}
	if h.HTTPResponseHeaders != nil {
		functions["HTTP_ResponseHeaders"] = h.HTTPResponseHeaders
	}
	if h.HTTPResponseStatus != nil {
		functions["HTTP_ResponseStatus"] = h.HTTPResponseStatus
	}
	if h.HTTPServe != nil {
		functions["HTTP_Serve"] = h.HTTPServe
	}
	if h.HexDecode != nil {
		functions["HexDecode"] = h.HexDecode
	}
	if h.HexEncode != nil {
		functions["HexEncode"] = h.HexEncode
	}
	if h.IntFromStr != nil {
		functions["IntFromStr"] = h.IntFromStr
	}
	if h.IntToDynamic != nil {
		functions["IntToDynamic"] = h.IntToDynamic
	}
	if h.IsNil != nil {
		functions["IsNil"] = h.IsNil
	}
	if h.JsonEncode != nil {
		functions["JsonEncode"] = h.JsonEncode
	}
	if h.JsonToDynamic != nil {
		functions["JsonToDynamic"] = h.JsonToDynamic
	}
	if h.ListToDynamic != nil {
		functions["ListToDynamic"] = h.ListToDynamic
	}
	if h.MapToDynamic != nil {
		functions["MapToDynamic"] = h.MapToDynamic
	}
	if h.Now != nil {
		functions["Now"] = h.Now
	}
	if h.OsArgs != nil {
		functions["OsArgs"] = h.OsArgs
	}
	if h.Print != nil {
		functions["Print"] = h.Print
	}
	if h.ReadLine != nil {
		functions["ReadLine"] = h.ReadLine
	}
	if h.Sleep != nil {
		functions["Sleep"] = h.Sleep
	}
	if h.SqlBeginTx != nil {
		functions["SqlBeginTx"] = h.SqlBeginTx
	}
	if h.SqlClose != nil {
		functions["SqlClose"] = h.SqlClose
	}
	if h.SqlCommit != nil {
		functions["SqlCommit"] = h.SqlCommit
	}
	if h.SqlCreateConnection != nil {
		functions["SqlCreateConnection"] = h.SqlCreateConnection
	}
	if h.SqlExecute != nil {
		functions["SqlExecute"] = h.SqlExecute
	}
	if h.SqlExtractParams != nil {
		functions["SqlExtractParams"] = h.SqlExtractParams
	}
	if h.SqlQuery != nil {
		functions["SqlQuery"] = h.SqlQuery
	}
	if h.SqlRollback != nil {
		functions["SqlRollback"] = h.SqlRollback
	}
	if h.StrToDynamic != nil {
		functions["StrToDynamic"] = h.StrToDynamic
	}
	if h.VoidToDynamic != nil {
		functions["VoidToDynamic"] = h.VoidToDynamic
	}
	if h.WaitFor != nil {
		functions["WaitFor"] = h.WaitFor
	}
	return functions
}

// Skipped extern AsyncEval: generic parameters are not generated yet.
// Skipped extern GetResult: generic parameters are not generated yet.
// Skipped extern JsonEncode: generic parameters are not generated yet.
// Skipped extern NewList: generic returns are not generated yet.
