// Code generated by ard; DO NOT EDIT.

package ffi

import (
	"database/sql"
	ardruntime "github.com/akonwi/ard/runtime"
	gohttp "net/http"
)

type Void = struct{}

type Maybe[T any] = ardruntime.Maybe[T]

func Some[T any](value T) Maybe[T] {
	return ardruntime.Some(value)
}

func None[T any]() Maybe[T] {
	return ardruntime.None[T]()
}

type Result[T, E any] = ardruntime.Result[T, E]

func Ok[T, E any](value T) Result[T, E] {
	return ardruntime.Ok[T, E](value)
}

func Err[T, E any](err E) Result[T, E] {
	return ardruntime.Err[T](err)
}

type WaitGroup = any

type Decoder = any

type HandlerFn = func(Request) Response

type JsonInput = any

type PathSegment = any

type Value = any

type Method int

type Argv struct {
	Program   string
	Arguments []string
}

type Database struct {
	Db     *sql.DB
	Driver string
	Path   string
}

type DirEntry struct {
	Name   string
	IsFile bool
}

type Error struct {
	Expected string
	Found    string
	Path     []string
}

type Fiber[T any] struct {
	Wg     WaitGroup
	Result T
}

type IntPartition struct {
	Selected []int
	Others   []int
}

type Partition[T any] struct {
	Selected []T
	Others   []T
}

type PersonJSONTest struct {
	Name     string
	Age      int
	Employed Maybe[bool]
}

type PredictionJSONTest struct {
	Advice Maybe[string]
	Winner Maybe[WinnerJSONTest]
}

type PreparedQuery struct {
	String string
	Values []any
}

type Query struct {
	Conn   Runner
	Driver string
	String string
	Params []string
}

type Request struct {
	Method  Method
	Url     string
	Headers map[string]string
	Body    Maybe[any]
	Timeout Maybe[int]
	Raw     Maybe[*gohttp.Request]
}

type Response struct {
	Status  int
	Headers map[string]string
	Body    string
}

type TodoJSONTest struct {
	Id    int
	Title string
	Note  Maybe[string]
}

type Transaction struct {
	Tx     *sql.Tx
	Driver string
}

type WinnerJSONTest struct {
	Id      int
	Name    string
	Comment string
}

// Skipped extern AsyncEval: generic parameters are not generated yet.
// Skipped extern GetResult: generic parameters are not generated yet.
// Skipped extern JsonEncode: generic parameters are not generated yet.
// Skipped extern JsonParse: generic returns are not generated yet.
