// Code generated by ard; DO NOT EDIT.

package ffi

import (
	"database/sql"
	ardruntime "github.com/akonwi/ard/runtime"
	gohttp "net/http"
)

type Void = ardruntime.Void

type Maybe[T any] = ardruntime.Maybe[T]

func Some[T any](value T) Maybe[T] {
	return ardruntime.Some(value)
}

func None[T any]() Maybe[T] {
	return ardruntime.None[T]()
}

type Result[T, E any] = ardruntime.Result[T, E]

func Ok[T, E any](value T) Result[T, E] {
	return ardruntime.Ok[T, E](value)
}

func Err[T, E any](err E) Result[T, E] {
	return ardruntime.Err[T](err)
}

type WaitGroup = any

type Conn = any

type Decoder = any

type HandlerFn = func(Request, *Response)

type JsonInput = any

type PathSegment = any

type Primitive = any

type RawRequest = *gohttp.Request

type RawResponse = *gohttp.Response

type Value = any

type Method int

type Argv struct {
	Program   string
	Arguments []string
}

type Database struct {
	Db     *sql.DB
	Driver string
	Path   string
}

type DirEntry struct {
	Name   string
	IsFile bool
}

type Error struct {
	Expected string
	Found    string
	Path     []string
}

type Fiber[T any] struct {
	Wg     WaitGroup
	Result T
}

type IntPartition struct {
	Selected []int
	Others   []int
}

type Partition[T any] struct {
	Selected []T
	Others   []T
}

type PersonJSONTest struct {
	Name     string
	Age      int
	Employed Maybe[bool]
}

type PredictionJSONTest struct {
	Advice Maybe[string]
	Winner Maybe[WinnerJSONTest]
}

type PreparedQuery struct {
	String string
	Values []any
}

type Query struct {
	Conn   any
	Driver string
	String string
	Params []string
}

type Request struct {
	Method  Method
	Url     string
	Headers map[string]string
	Body    Maybe[any]
	Timeout Maybe[int]
	Raw     Maybe[*gohttp.Request]
}

type Response struct {
	Status  int
	Headers map[string]string
	Body    string
}

type TodoJSONTest struct {
	Id    int
	Title string
	Note  Maybe[string]
}

type Transaction struct {
	Tx     *sql.Tx
	Driver string
}

type WinnerJSONTest struct {
	Id      int
	Name    string
	Comment string
}

type Host struct {
	AsyncStart           func(do func()) Fiber[Void]
	ByteFromInt          func(value int) Maybe[byte]
	BytesToDynamic       func(bytes []byte) any
	CryptoHashPassword   func(password string, cost Maybe[int]) (string, error)
	CryptoMd5            func(input []byte) []byte
	CryptoScryptHash     func(password string, salt_hex Maybe[string], n Maybe[int], r Maybe[int], p Maybe[int], dk_len Maybe[int]) (string, error)
	CryptoScryptVerify   func(password string, hash string, n Maybe[int], r Maybe[int], p Maybe[int], dk_len Maybe[int]) (bool, error)
	CryptoSha256         func(input []byte) []byte
	CryptoSha512         func(input []byte) []byte
	CryptoUUID           func() string
	CryptoVerifyPassword func(password string, hashed string) (bool, error)
	DecodeBool           func(data any) Result[bool, Error]
	DecodeByte           func(data any) Result[byte, Error]
	DecodeFloat          func(data any) Result[float64, Error]
	DecodeInt            func(data any) Result[int, Error]
	DecodeRune           func(data any) Result[rune, Error]
	DecodeString         func(data any) Result[string, Error]
	DynamicToList        func(data any) ([]any, error)
	DynamicToMap         func(data any) (map[any]any, error)
	ExtractField         func(data any, name string) (any, error)
	FSExists             func(path string) bool
	FSIsDir              func(path string) bool
	FSIsFile             func(path string) bool
	FSListDir            func(path string) (map[string]bool, error)
	FloatFromInt         func(int int) float64
	HTTPDo               func(method string, url string, body any, headers map[string]string, timeout Maybe[int]) (*gohttp.Response, error)
	HTTPResponseBody     func(resp *gohttp.Response) (string, error)
	HTTPResponseClose    func(resp *gohttp.Response)
	HTTPResponseHeaders  func(resp *gohttp.Response) map[string]string
	HTTPServe            func(port int, handlers map[string]func(Request, *Response)) error
	IsNil                func(data any) bool
	JsonEncode           func(value any) (string, error)
	JsonToDynamic        func(json string) (any, error)
	ListToDynamic        func(list []any) any
	MapToDynamic         func(from map[string]any) any
	OsArgs               func() []string
	Print                func(string string)
	ReadLine             func() (string, error)
	RuneFromInt          func(value int) Maybe[rune]
	RuneFromStr          func(value string) Maybe[rune]
	SqlBeginTx           func(db *sql.DB) (*sql.Tx, error)
	SqlClose             func(db *sql.DB) error
	SqlCommit            func(tx *sql.Tx) error
	SqlCreateConnection  func(driver string, connection_string string) (*sql.DB, error)
	SqlExecute           func(conn any, driver string, sql string, values []any) error
	SqlQuery             func(conn any, driver string, sql string, values []any) ([]any, error)
	SqlRollback          func(tx *sql.Tx) error
	StrFromRunes         func(runes []rune) (string, error)
	StrFromUtf8          func(bytes []byte) (string, error)
	VoidToDynamic        func() any
	WaitFor              func(wg WaitGroup)
}

func (h Host) Functions() map[string]any {
	functions := map[string]any{}
	if h.AsyncStart != nil {
		functions["AsyncStart"] = h.AsyncStart
	}
	if h.ByteFromInt != nil {
		functions["ByteFromInt"] = h.ByteFromInt
	}
	if h.BytesToDynamic != nil {
		functions["BytesToDynamic"] = h.BytesToDynamic
	}
	if h.CryptoHashPassword != nil {
		functions["CryptoHashPassword"] = h.CryptoHashPassword
	}
	if h.CryptoMd5 != nil {
		functions["CryptoMd5"] = h.CryptoMd5
	}
	if h.CryptoScryptHash != nil {
		functions["CryptoScryptHash"] = h.CryptoScryptHash
	}
	if h.CryptoScryptVerify != nil {
		functions["CryptoScryptVerify"] = h.CryptoScryptVerify
	}
	if h.CryptoSha256 != nil {
		functions["CryptoSha256"] = h.CryptoSha256
	}
	if h.CryptoSha512 != nil {
		functions["CryptoSha512"] = h.CryptoSha512
	}
	if h.CryptoUUID != nil {
		functions["CryptoUUID"] = h.CryptoUUID
	}
	if h.CryptoVerifyPassword != nil {
		functions["CryptoVerifyPassword"] = h.CryptoVerifyPassword
	}
	if h.DecodeBool != nil {
		functions["DecodeBool"] = h.DecodeBool
	}
	if h.DecodeByte != nil {
		functions["DecodeByte"] = h.DecodeByte
	}
	if h.DecodeFloat != nil {
		functions["DecodeFloat"] = h.DecodeFloat
	}
	if h.DecodeInt != nil {
		functions["DecodeInt"] = h.DecodeInt
	}
	if h.DecodeRune != nil {
		functions["DecodeRune"] = h.DecodeRune
	}
	if h.DecodeString != nil {
		functions["DecodeString"] = h.DecodeString
	}
	if h.DynamicToList != nil {
		functions["DynamicToList"] = h.DynamicToList
	}
	if h.DynamicToMap != nil {
		functions["DynamicToMap"] = h.DynamicToMap
	}
	if h.ExtractField != nil {
		functions["ExtractField"] = h.ExtractField
	}
	if h.FSExists != nil {
		functions["FS_Exists"] = h.FSExists
	}
	if h.FSIsDir != nil {
		functions["FS_IsDir"] = h.FSIsDir
	}
	if h.FSIsFile != nil {
		functions["FS_IsFile"] = h.FSIsFile
	}
	if h.FSListDir != nil {
		functions["FS_ListDir"] = h.FSListDir
	}
	if h.FloatFromInt != nil {
		functions["FloatFromInt"] = h.FloatFromInt
	}
	if h.HTTPDo != nil {
		functions["HTTP_Do"] = h.HTTPDo
	}
	if h.HTTPResponseBody != nil {
		functions["HTTP_ResponseBody"] = h.HTTPResponseBody
	}
	if h.HTTPResponseClose != nil {
		functions["HTTP_ResponseClose"] = h.HTTPResponseClose
	}
	if h.HTTPResponseHeaders != nil {
		functions["HTTP_ResponseHeaders"] = h.HTTPResponseHeaders
	}
	if h.HTTPServe != nil {
		functions["HTTP_Serve"] = h.HTTPServe
	}
	if h.IsNil != nil {
		functions["IsNil"] = h.IsNil
	}
	if h.JsonEncode != nil {
		functions["JsonEncode"] = h.JsonEncode
	}
	if h.JsonToDynamic != nil {
		functions["JsonToDynamic"] = h.JsonToDynamic
	}
	if h.ListToDynamic != nil {
		functions["ListToDynamic"] = h.ListToDynamic
	}
	if h.MapToDynamic != nil {
		functions["MapToDynamic"] = h.MapToDynamic
	}
	if h.OsArgs != nil {
		functions["OsArgs"] = h.OsArgs
	}
	if h.Print != nil {
		functions["Print"] = h.Print
	}
	if h.ReadLine != nil {
		functions["ReadLine"] = h.ReadLine
	}
	if h.RuneFromInt != nil {
		functions["RuneFromInt"] = h.RuneFromInt
	}
	if h.RuneFromStr != nil {
		functions["RuneFromStr"] = h.RuneFromStr
	}
	if h.SqlBeginTx != nil {
		functions["SqlBeginTx"] = h.SqlBeginTx
	}
	if h.SqlClose != nil {
		functions["SqlClose"] = h.SqlClose
	}
	if h.SqlCommit != nil {
		functions["SqlCommit"] = h.SqlCommit
	}
	if h.SqlCreateConnection != nil {
		functions["SqlCreateConnection"] = h.SqlCreateConnection
	}
	if h.SqlExecute != nil {
		functions["SqlExecute"] = h.SqlExecute
	}
	if h.SqlQuery != nil {
		functions["SqlQuery"] = h.SqlQuery
	}
	if h.SqlRollback != nil {
		functions["SqlRollback"] = h.SqlRollback
	}
	if h.StrFromRunes != nil {
		functions["StrFromRunes"] = h.StrFromRunes
	}
	if h.StrFromUtf8 != nil {
		functions["StrFromUtf8"] = h.StrFromUtf8
	}
	if h.VoidToDynamic != nil {
		functions["VoidToDynamic"] = h.VoidToDynamic
	}
	if h.WaitFor != nil {
		functions["WaitFor"] = h.WaitFor
	}
	return functions
}

// Skipped extern AsyncEval: generic parameters are not generated yet.
// Skipped extern GetResult: generic parameters are not generated yet.
// Skipped extern IsNil: generic parameters are not generated yet.
// Skipped extern JsonEncode: generic parameters are not generated yet.
// Skipped extern JsonParse: generic returns are not generated yet.
