// Code generated by ard; DO NOT EDIT.

package ffi

import (
	"fmt"
	"github.com/akonwi/ard/air"
	vmffi "github.com/akonwi/ard/vm/ffi"
	"reflect"
)

func init() {
	vmffi.RegisterAdapterLookup(VMAdapter)
}
func generatedHostCast[T any](value any) (T, bool) {
	var zero T
	if value == nil {
		return zero, true
	}
	out, ok := value.(T)
	return out, ok
}
func VMAdapter(binding string, fn any) (vmffi.ExternAdapter, bool) {
	switch binding {
	case "AsyncStart":
		typed, ok := fn.(func(func() (struct{}, error)) Fiber[struct{}])
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[func() (struct{}, error)]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[func() (struct{}, error)](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "Base64Decode":
		typed, ok := fn.(func(string, Maybe[bool]) (string, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1Raw, err := bridge.HostArg(args, 1, reflect.TypeFor[Maybe[bool]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg1, ok := generatedHostCast[Maybe[bool]](arg1Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 1: cannot use generated host arg %T", binding, arg1Raw)
			}
			out0, out1 := typed(arg0, arg1)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "Base64DecodeURL":
		typed, ok := fn.(func(string, Maybe[bool]) (string, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1Raw, err := bridge.HostArg(args, 1, reflect.TypeFor[Maybe[bool]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg1, ok := generatedHostCast[Maybe[bool]](arg1Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 1: cannot use generated host arg %T", binding, arg1Raw)
			}
			out0, out1 := typed(arg0, arg1)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "Base64Encode":
		typed, ok := fn.(func(string, Maybe[bool]) string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1Raw, err := bridge.HostArg(args, 1, reflect.TypeFor[Maybe[bool]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg1, ok := generatedHostCast[Maybe[bool]](arg1Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 1: cannot use generated host arg %T", binding, arg1Raw)
			}
			out0 := typed(arg0, arg1)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "Base64EncodeURL":
		typed, ok := fn.(func(string, Maybe[bool]) string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1Raw, err := bridge.HostArg(args, 1, reflect.TypeFor[Maybe[bool]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg1, ok := generatedHostCast[Maybe[bool]](arg1Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 1: cannot use generated host arg %T", binding, arg1Raw)
			}
			out0 := typed(arg0, arg1)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "BoolToDynamic":
		typed, ok := fn.(func(bool) any)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgBool(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "CryptoHashPassword":
		typed, ok := fn.(func(string, Maybe[int]) (string, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1Raw, err := bridge.HostArg(args, 1, reflect.TypeFor[Maybe[int]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg1, ok := generatedHostCast[Maybe[int]](arg1Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 1: cannot use generated host arg %T", binding, arg1Raw)
			}
			out0, out1 := typed(arg0, arg1)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "CryptoMd5":
		typed, ok := fn.(func(string) string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "CryptoScryptHash":
		typed, ok := fn.(func(string, Maybe[string], Maybe[int], Maybe[int], Maybe[int], Maybe[int]) (string, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1Raw, err := bridge.HostArg(args, 1, reflect.TypeFor[Maybe[string]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg1, ok := generatedHostCast[Maybe[string]](arg1Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 1: cannot use generated host arg %T", binding, arg1Raw)
			}
			arg2Raw, err := bridge.HostArg(args, 2, reflect.TypeFor[Maybe[int]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 2: %w", binding, err)
			}
			arg2, ok := generatedHostCast[Maybe[int]](arg2Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 2: cannot use generated host arg %T", binding, arg2Raw)
			}
			arg3Raw, err := bridge.HostArg(args, 3, reflect.TypeFor[Maybe[int]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 3: %w", binding, err)
			}
			arg3, ok := generatedHostCast[Maybe[int]](arg3Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 3: cannot use generated host arg %T", binding, arg3Raw)
			}
			arg4Raw, err := bridge.HostArg(args, 4, reflect.TypeFor[Maybe[int]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 4: %w", binding, err)
			}
			arg4, ok := generatedHostCast[Maybe[int]](arg4Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 4: cannot use generated host arg %T", binding, arg4Raw)
			}
			arg5Raw, err := bridge.HostArg(args, 5, reflect.TypeFor[Maybe[int]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 5: %w", binding, err)
			}
			arg5, ok := generatedHostCast[Maybe[int]](arg5Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 5: cannot use generated host arg %T", binding, arg5Raw)
			}
			out0, out1 := typed(arg0, arg1, arg2, arg3, arg4, arg5)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "CryptoScryptVerify":
		typed, ok := fn.(func(string, string, Maybe[int], Maybe[int], Maybe[int], Maybe[int]) (bool, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg2Raw, err := bridge.HostArg(args, 2, reflect.TypeFor[Maybe[int]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 2: %w", binding, err)
			}
			arg2, ok := generatedHostCast[Maybe[int]](arg2Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 2: cannot use generated host arg %T", binding, arg2Raw)
			}
			arg3Raw, err := bridge.HostArg(args, 3, reflect.TypeFor[Maybe[int]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 3: %w", binding, err)
			}
			arg3, ok := generatedHostCast[Maybe[int]](arg3Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 3: cannot use generated host arg %T", binding, arg3Raw)
			}
			arg4Raw, err := bridge.HostArg(args, 4, reflect.TypeFor[Maybe[int]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 4: %w", binding, err)
			}
			arg4, ok := generatedHostCast[Maybe[int]](arg4Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 4: cannot use generated host arg %T", binding, arg4Raw)
			}
			arg5Raw, err := bridge.HostArg(args, 5, reflect.TypeFor[Maybe[int]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 5: %w", binding, err)
			}
			arg5, ok := generatedHostCast[Maybe[int]](arg5Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 5: cannot use generated host arg %T", binding, arg5Raw)
			}
			out0, out1 := typed(arg0, arg1, arg2, arg3, arg4, arg5)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "CryptoSha256":
		typed, ok := fn.(func(string) string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "CryptoSha512":
		typed, ok := fn.(func(string) string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "CryptoUUID":
		typed, ok := fn.(func() string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			out0 := typed()
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "CryptoVerifyPassword":
		typed, ok := fn.(func(string, string) (bool, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0, out1 := typed(arg0, arg1)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "DecodeBool":
		typed, ok := fn.(func(any) Result[bool, Error])
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgAny(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnResult(extern.Signature.Return, out0.Value, out0.Err, out0.Ok)
		}, true
	case "DecodeFloat":
		typed, ok := fn.(func(any) Result[float64, Error])
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgAny(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnResult(extern.Signature.Return, out0.Value, out0.Err, out0.Ok)
		}, true
	case "DecodeInt":
		typed, ok := fn.(func(any) Result[int, Error])
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgAny(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnResult(extern.Signature.Return, out0.Value, out0.Err, out0.Ok)
		}, true
	case "DecodeString":
		typed, ok := fn.(func(any) Result[string, Error])
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgAny(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnResult(extern.Signature.Return, out0.Value, out0.Err, out0.Ok)
		}, true
	case "DynamicToList":
		typed, ok := fn.(func(any) ([]any, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgAny(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "DynamicToMap":
		typed, ok := fn.(func(any) (map[string]any, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgAny(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "EnvGet":
		typed, ok := fn.(func(string) Maybe[string])
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "ExtractField":
		typed, ok := fn.(func(any, string) (any, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgAny(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0, out1 := typed(arg0, arg1)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "FS_Abs":
		typed, ok := fn.(func(string) (string, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "FS_AppendFile":
		typed, ok := fn.(func(string, string) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "FS_Copy":
		typed, ok := fn.(func(string, string) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "FS_CreateDir":
		typed, ok := fn.(func(string) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "FS_CreateFile":
		typed, ok := fn.(func(string) (bool, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "FS_Cwd":
		typed, ok := fn.(func() (string, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			out0, out1 := typed()
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "FS_DeleteDir":
		typed, ok := fn.(func(string) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "FS_DeleteFile":
		typed, ok := fn.(func(string) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "FS_Exists":
		typed, ok := fn.(func(string) bool)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "FS_IsDir":
		typed, ok := fn.(func(string) bool)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "FS_IsFile":
		typed, ok := fn.(func(string) bool)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "FS_ListDir":
		typed, ok := fn.(func(string) (map[string]bool, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "FS_ReadFile":
		typed, ok := fn.(func(string) (string, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "FS_Rename":
		typed, ok := fn.(func(string, string) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "FS_WriteFile":
		typed, ok := fn.(func(string, string) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "FloatFloor":
		typed, ok := fn.(func(float64) float64)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgFloat64(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "FloatFromInt":
		typed, ok := fn.(func(int) float64)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgInt(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "FloatFromStr":
		typed, ok := fn.(func(string) Maybe[float64])
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "FloatToDynamic":
		typed, ok := fn.(func(float64) any)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgFloat64(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "GetPathValue":
		typed, ok := fn.(func(RawRequest, string) string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[RawRequest]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[RawRequest](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "GetQueryParam":
		typed, ok := fn.(func(RawRequest, string) string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[RawRequest]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[RawRequest](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "GetReqPath":
		typed, ok := fn.(func(RawRequest) string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[RawRequest]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[RawRequest](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "GetTodayString":
		typed, ok := fn.(func() string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			out0 := typed()
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "HTTP_Do":
		typed, ok := fn.(func(string, string, any, map[string]string, Maybe[int]) (RawResponse, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg2, err := bridge.HostArgAny(args, 2)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 2: %w", binding, err)
			}
			arg3Raw, err := bridge.HostArg(args, 3, reflect.TypeFor[map[string]string]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 3: %w", binding, err)
			}
			arg3, ok := generatedHostCast[map[string]string](arg3Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 3: cannot use generated host arg %T", binding, arg3Raw)
			}
			arg4Raw, err := bridge.HostArg(args, 4, reflect.TypeFor[Maybe[int]]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 4: %w", binding, err)
			}
			arg4, ok := generatedHostCast[Maybe[int]](arg4Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 4: cannot use generated host arg %T", binding, arg4Raw)
			}
			out0, out1 := typed(arg0, arg1, arg2, arg3, arg4)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "HTTP_ResponseBody":
		typed, ok := fn.(func(RawResponse) (string, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[RawResponse]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[RawResponse](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "HTTP_ResponseClose":
		typed, ok := fn.(func(RawResponse))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[RawResponse]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[RawResponse](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			typed(arg0)
			return bridge.HostReturnVoid(extern.Signature.Return)
		}, true
	case "HTTP_ResponseHeaders":
		typed, ok := fn.(func(RawResponse) map[string]string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[RawResponse]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[RawResponse](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "HTTP_ResponseStatus":
		typed, ok := fn.(func(RawResponse) int)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[RawResponse]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[RawResponse](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "HTTP_Serve":
		typed, ok := fn.(func(int, map[string]func(Request, *Response) (struct{}, error)) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgInt(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1Raw, err := bridge.HostArg(args, 1, reflect.TypeFor[map[string]func(Request, *Response) (struct{}, error)]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg1, ok := generatedHostCast[map[string]func(Request, *Response) (struct{}, error)](arg1Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 1: cannot use generated host arg %T", binding, arg1Raw)
			}
			out0 := typed(arg0, arg1)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "HexDecode":
		typed, ok := fn.(func(string) (string, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "HexEncode":
		typed, ok := fn.(func(string) string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "IntFromStr":
		typed, ok := fn.(func(string) Maybe[int])
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "IntToDynamic":
		typed, ok := fn.(func(int) any)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgInt(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "IsNil":
		typed, ok := fn.(func(any) bool)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgAny(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "JsonEncode":
		typed, ok := fn.(func(any) (string, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgAny(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "JsonToDynamic":
		typed, ok := fn.(func(string) (any, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "ListToDynamic":
		typed, ok := fn.(func([]any) any)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[[]any]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[[]any](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "MapToDynamic":
		typed, ok := fn.(func(map[string]any) any)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[map[string]any]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[map[string]any](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "Now":
		typed, ok := fn.(func() int)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			out0 := typed()
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "OsArgs":
		typed, ok := fn.(func() []string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			out0 := typed()
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "Print":
		typed, ok := fn.(func(string))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			typed(arg0)
			return bridge.HostReturnVoid(extern.Signature.Return)
		}, true
	case "ReadLine":
		typed, ok := fn.(func() (string, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			out0, out1 := typed()
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "Sleep":
		typed, ok := fn.(func(int))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgInt(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			typed(arg0)
			return bridge.HostReturnVoid(extern.Signature.Return)
		}, true
	case "SqlBeginTx":
		typed, ok := fn.(func(Db) (Tx, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[Db]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[Db](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "SqlClose":
		typed, ok := fn.(func(Db) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[Db]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[Db](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			out0 := typed(arg0)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "SqlCommit":
		typed, ok := fn.(func(Tx) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[Tx]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[Tx](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			out0 := typed(arg0)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "SqlCreateConnection":
		typed, ok := fn.(func(string) (Db, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "SqlExecute":
		typed, ok := fn.(func(any, string, []any) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgAny(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg2Raw, err := bridge.HostArg(args, 2, reflect.TypeFor[[]any]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 2: %w", binding, err)
			}
			arg2, ok := generatedHostCast[[]any](arg2Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 2: cannot use generated host arg %T", binding, arg2Raw)
			}
			out0 := typed(arg0, arg1, arg2)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "SqlExtractParams":
		typed, ok := fn.(func(string) []string)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "SqlQuery":
		typed, ok := fn.(func(any, string, []any) ([]any, error))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgAny(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := bridge.HostArgString(args, 1)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg2Raw, err := bridge.HostArg(args, 2, reflect.TypeFor[[]any]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 2: %w", binding, err)
			}
			arg2, ok := generatedHostCast[[]any](arg2Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 2: cannot use generated host arg %T", binding, arg2Raw)
			}
			out0, out1 := typed(arg0, arg1, arg2)
			return bridge.HostReturnValueError(extern.Signature.Return, out0, out1)
		}, true
	case "SqlRollback":
		typed, ok := fn.(func(Tx) error)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[Tx]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[Tx](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			out0 := typed(arg0)
			return bridge.HostReturnError(extern.Signature.Return, out0)
		}, true
	case "StrToDynamic":
		typed, ok := fn.(func(string) any)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0, err := bridge.HostArgString(args, 0)
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "VoidToDynamic":
		typed, ok := fn.(func() any)
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			out0 := typed()
			return bridge.HostReturnValue(extern.Signature.Return, out0)
		}, true
	case "WaitFor":
		typed, ok := fn.(func(WaitGroup))
		if !ok {
			return nil, false
		}
		return func(bridge vmffi.Bridge, extern air.Extern, binding string, args any) (any, error) {
			arg0Raw, err := bridge.HostArg(args, 0, reflect.TypeFor[WaitGroup]())
			if err != nil {
				return nil, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg0, ok := generatedHostCast[WaitGroup](arg0Raw)
			if !ok {
				return nil, fmt.Errorf("extern %s arg 0: cannot use generated host arg %T", binding, arg0Raw)
			}
			typed(arg0)
			return bridge.HostReturnVoid(extern.Signature.Return)
		}, true
	}
	return nil, false
}
