//go:build ignore

package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	paths := []string{"go.mod", "go.sum", "runtime/equal.go", "runtime/maybe.go", "runtime/result.go", "runtime/structural_map.go"}
	for _, dir := range []string{filepath.Join("std_lib", "ffi")} {
		matches, err := filepath.Glob(filepath.Join("..", dir, "*.go"))
		if err != nil {
			panic(err)
		}
		for _, path := range matches {
			base := filepath.Base(path)
			if strings.HasSuffix(base, "_test.go") || base == "generate.go" {
				continue
			}
			paths = append(paths, filepath.ToSlash(filepath.Join(dir, base)))
		}
	}
	sort.Strings(paths)

	var out strings.Builder
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	out.WriteString("package gotarget\n\n")
	out.WriteString("var embeddedArdModuleFiles = map[string]string{\n")
	for _, rel := range paths {
		data, err := os.ReadFile(filepath.Join("..", filepath.FromSlash(rel)))
		if err != nil {
			panic(err)
		}
		fmt.Fprintf(&out, "\t%q: %s,\n", rel, strconv.Quote(string(data)))
	}
	out.WriteString("}\n")

	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("ard_module_files.gen.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
