// Code generated by ard; DO NOT EDIT.

package gotarget

import (
	"go/ast"

	"github.com/akonwi/ard/air"
)

type generatedStdlibExternKind uint8

const (
	generatedStdlibExternCall generatedStdlibExternKind = iota
	generatedStdlibExternJSONEncode
	generatedStdlibExternJSONParse
)

type generatedStdlibExternReturn uint8

const (
	generatedStdlibReturnDirect generatedStdlibExternReturn = iota
	generatedStdlibReturnError
	generatedStdlibReturnValueError
	generatedStdlibReturnResult
)

type generatedStdlibExternParamAdapter uint8

const (
	generatedStdlibParamDirect generatedStdlibExternParamAdapter = iota
	generatedStdlibParamAny
	generatedStdlibParamAnySlice
)

type generatedStdlibExternLowering struct {
	kind     generatedStdlibExternKind
	function string
	returns  generatedStdlibExternReturn
	params   []generatedStdlibExternParamAdapter
}

var generatedStdlibExternLowerings = map[string]generatedStdlibExternLowering{
	"HTTP_Do":              {function: "HTTPDo", returns: generatedStdlibReturnValueError, params: []generatedStdlibExternParamAdapter{generatedStdlibParamDirect, generatedStdlibParamDirect, generatedStdlibParamAny, generatedStdlibParamDirect, generatedStdlibParamDirect}},
	"HTTP_ResponseBody":    {function: "HTTPResponseBody", returns: generatedStdlibReturnValueError, params: []generatedStdlibExternParamAdapter{generatedStdlibParamDirect}},
	"HTTP_ResponseClose":   {function: "HTTPResponseClose", returns: generatedStdlibReturnDirect, params: []generatedStdlibExternParamAdapter{generatedStdlibParamDirect}},
	"HTTP_ResponseHeaders": {function: "HTTPResponseHeaders", returns: generatedStdlibReturnDirect, params: []generatedStdlibExternParamAdapter{generatedStdlibParamDirect}},
	"HTTP_Serve":           {function: "HTTPServe", returns: generatedStdlibReturnError, params: []generatedStdlibExternParamAdapter{generatedStdlibParamDirect, generatedStdlibParamDirect}},
	"SqlBeginTx":           {function: "SqlBeginTx", returns: generatedStdlibReturnValueError, params: []generatedStdlibExternParamAdapter{generatedStdlibParamDirect}},
	"SqlClose":             {function: "SqlClose", returns: generatedStdlibReturnError, params: []generatedStdlibExternParamAdapter{generatedStdlibParamDirect}},
	"SqlCommit":            {function: "SqlCommit", returns: generatedStdlibReturnError, params: []generatedStdlibExternParamAdapter{generatedStdlibParamDirect}},
	"SqlCreateConnection":  {function: "SqlCreateConnection", returns: generatedStdlibReturnValueError, params: []generatedStdlibExternParamAdapter{generatedStdlibParamDirect, generatedStdlibParamDirect}},
	"SqlExecute":           {function: "SqlExecute", returns: generatedStdlibReturnError, params: []generatedStdlibExternParamAdapter{generatedStdlibParamAny, generatedStdlibParamDirect, generatedStdlibParamDirect, generatedStdlibParamAnySlice}},
	"SqlQuery":             {function: "SqlQuery", returns: generatedStdlibReturnValueError, params: []generatedStdlibExternParamAdapter{generatedStdlibParamAny, generatedStdlibParamDirect, generatedStdlibParamDirect, generatedStdlibParamAnySlice}},
	"SqlRollback":          {function: "SqlRollback", returns: generatedStdlibReturnError, params: []generatedStdlibExternParamAdapter{generatedStdlibParamDirect}},
	"JsonEncode":           {kind: generatedStdlibExternJSONEncode},
	"JsonParse":            {kind: generatedStdlibExternJSONParse},
}

func (l *lowerer) lowerGeneratedStdlibExtern(binding string, signature air.Signature, args []ast.Expr, stmts []ast.Stmt, returnTypeID air.TypeID) (loweredExpr, bool, error) {
	lowering, ok := generatedStdlibExternLowerings[binding]
	if !ok {
		return loweredExpr{}, false, nil
	}
	switch lowering.kind {
	case generatedStdlibExternJSONEncode:
		wrapped, err := l.lowerJSONEncodeStdlibExtern(signature, args, stmts, returnTypeID)
		return wrapped, true, err
	case generatedStdlibExternJSONParse:
		wrapped, err := l.lowerJSONParseStdlibExtern(args, stmts, returnTypeID)
		return wrapped, true, err
	}
	adaptedArgs := append([]ast.Expr(nil), args...)
	for i, adapter := range lowering.params {
		if i >= len(adaptedArgs) || i >= len(signature.Params) {
			break
		}
		switch adapter {
		case generatedStdlibParamAny:
			arg, err := l.lowerUnionArgToAny(adaptedArgs[i], signature.Params[i].Type)
			if err != nil {
				return loweredExpr{}, true, err
			}
			stmts = append(stmts, arg.stmts...)
			adaptedArgs[i] = arg.expr
		case generatedStdlibParamAnySlice:
			arg, err := l.lowerUnionSliceArgToAny(adaptedArgs[i], signature.Params[i].Type)
			if err != nil {
				return loweredExpr{}, true, err
			}
			stmts = append(stmts, arg.stmts...)
			adaptedArgs[i] = arg.expr
		}
	}
	call := &ast.CallExpr{Fun: l.qualified("stdlibffi", "github.com/akonwi/ard/std_lib/ffi", lowering.function), Args: adaptedArgs}
	switch lowering.returns {
	case generatedStdlibReturnError:
		wrapped, err := l.wrapErrorCall(returnTypeID, call)
		if err != nil {
			return loweredExpr{}, true, err
		}
		wrapped.stmts = append(stmts, wrapped.stmts...)
		return wrapped, true, nil
	case generatedStdlibReturnValueError:
		wrapped, err := l.wrapValueErrorCall(returnTypeID, call)
		if err != nil {
			return loweredExpr{}, true, err
		}
		wrapped.stmts = append(stmts, wrapped.stmts...)
		return wrapped, true, nil
	case generatedStdlibReturnResult:
		wrapped, err := l.wrapStdlibResultCall(returnTypeID, call)
		if err != nil {
			return loweredExpr{}, true, err
		}
		wrapped.stmts = append(stmts, wrapped.stmts...)
		return wrapped, true, nil
	default:
		return loweredExpr{stmts: stmts, expr: call}, true, nil
	}
}
