// Code generated by ard; DO NOT EDIT.

package gotarget

import (
	"go/ast"

	"github.com/akonwi/ard/air"
)

type generatedStdlibExternReturn uint8

const (
	generatedStdlibReturnDirect generatedStdlibExternReturn = iota
	generatedStdlibReturnError
	generatedStdlibReturnValueError
	generatedStdlibReturnResult
)

type generatedStdlibExternLowering struct {
	function string
	returns  generatedStdlibExternReturn
}

var generatedStdlibExternLowerings = map[string]generatedStdlibExternLowering{
	"Base64Decode":         {function: "Base64Decode", returns: generatedStdlibReturnValueError},
	"Base64DecodeURL":      {function: "Base64DecodeURL", returns: generatedStdlibReturnValueError},
	"Base64Encode":         {function: "Base64Encode", returns: generatedStdlibReturnDirect},
	"Base64EncodeURL":      {function: "Base64EncodeURL", returns: generatedStdlibReturnDirect},
	"BoolToDynamic":        {function: "BoolToDynamic", returns: generatedStdlibReturnDirect},
	"CryptoHashPassword":   {function: "CryptoHashPassword", returns: generatedStdlibReturnValueError},
	"CryptoMd5":            {function: "CryptoMd5", returns: generatedStdlibReturnDirect},
	"CryptoScryptHash":     {function: "CryptoScryptHash", returns: generatedStdlibReturnValueError},
	"CryptoScryptVerify":   {function: "CryptoScryptVerify", returns: generatedStdlibReturnValueError},
	"CryptoSha256":         {function: "CryptoSha256", returns: generatedStdlibReturnDirect},
	"CryptoSha512":         {function: "CryptoSha512", returns: generatedStdlibReturnDirect},
	"CryptoUUID":           {function: "CryptoUUID", returns: generatedStdlibReturnDirect},
	"CryptoVerifyPassword": {function: "CryptoVerifyPassword", returns: generatedStdlibReturnValueError},
	"DecodeBool":           {function: "DecodeBool", returns: generatedStdlibReturnResult},
	"DecodeFloat":          {function: "DecodeFloat", returns: generatedStdlibReturnResult},
	"DecodeInt":            {function: "DecodeInt", returns: generatedStdlibReturnResult},
	"DecodeString":         {function: "DecodeString", returns: generatedStdlibReturnResult},
	"DynamicToList":        {function: "DynamicToList", returns: generatedStdlibReturnValueError},
	"EnvGet":               {function: "EnvGet", returns: generatedStdlibReturnDirect},
	"ExtractField":         {function: "ExtractField", returns: generatedStdlibReturnValueError},
	"FS_Abs":               {function: "FSAbs", returns: generatedStdlibReturnValueError},
	"FS_AppendFile":        {function: "FSAppendFile", returns: generatedStdlibReturnError},
	"FS_Copy":              {function: "FSCopy", returns: generatedStdlibReturnError},
	"FS_CreateDir":         {function: "FSCreateDir", returns: generatedStdlibReturnError},
	"FS_CreateFile":        {function: "FSCreateFile", returns: generatedStdlibReturnValueError},
	"FS_Cwd":               {function: "FSCwd", returns: generatedStdlibReturnValueError},
	"FS_DeleteDir":         {function: "FSDeleteDir", returns: generatedStdlibReturnError},
	"FS_DeleteFile":        {function: "FSDeleteFile", returns: generatedStdlibReturnError},
	"FS_Exists":            {function: "FSExists", returns: generatedStdlibReturnDirect},
	"FS_IsDir":             {function: "FSIsDir", returns: generatedStdlibReturnDirect},
	"FS_IsFile":            {function: "FSIsFile", returns: generatedStdlibReturnDirect},
	"FS_ListDir":           {function: "FSListDir", returns: generatedStdlibReturnValueError},
	"FS_ReadFile":          {function: "FSReadFile", returns: generatedStdlibReturnValueError},
	"FS_Rename":            {function: "FSRename", returns: generatedStdlibReturnError},
	"FS_WriteFile":         {function: "FSWriteFile", returns: generatedStdlibReturnError},
	"FloatFloor":           {function: "FloatFloor", returns: generatedStdlibReturnDirect},
	"FloatFromInt":         {function: "FloatFromInt", returns: generatedStdlibReturnDirect},
	"FloatFromStr":         {function: "FloatFromStr", returns: generatedStdlibReturnDirect},
	"FloatToDynamic":       {function: "FloatToDynamic", returns: generatedStdlibReturnDirect},
	"GetPathValue":         {function: "GetPathValue", returns: generatedStdlibReturnDirect},
	"GetQueryParam":        {function: "GetQueryParam", returns: generatedStdlibReturnDirect},
	"GetReqPath":           {function: "GetReqPath", returns: generatedStdlibReturnDirect},
	"HTTP_Do":              {function: "HTTPDo", returns: generatedStdlibReturnValueError},
	"HTTP_ResponseBody":    {function: "HTTPResponseBody", returns: generatedStdlibReturnValueError},
	"HTTP_ResponseClose":   {function: "HTTPResponseClose", returns: generatedStdlibReturnDirect},
	"HTTP_ResponseHeaders": {function: "HTTPResponseHeaders", returns: generatedStdlibReturnDirect},
	"HTTP_ResponseStatus":  {function: "HTTPResponseStatus", returns: generatedStdlibReturnDirect},
	"HexDecode":            {function: "HexDecode", returns: generatedStdlibReturnValueError},
	"HexEncode":            {function: "HexEncode", returns: generatedStdlibReturnDirect},
	"IntFromStr":           {function: "IntFromStr", returns: generatedStdlibReturnDirect},
	"IntToDynamic":         {function: "IntToDynamic", returns: generatedStdlibReturnDirect},
	"IsNil":                {function: "IsNil", returns: generatedStdlibReturnDirect},
	"JsonToDynamic":        {function: "JsonToDynamic", returns: generatedStdlibReturnValueError},
	"ListToDynamic":        {function: "ListToDynamic", returns: generatedStdlibReturnDirect},
	"MapToDynamic":         {function: "MapToDynamic", returns: generatedStdlibReturnDirect},
	"OsArgs":               {function: "OsArgs", returns: generatedStdlibReturnDirect},
	"Print":                {function: "Print", returns: generatedStdlibReturnDirect},
	"ReadLine":             {function: "ReadLine", returns: generatedStdlibReturnValueError},
	"Sleep":                {function: "Sleep", returns: generatedStdlibReturnDirect},
	"SqlBeginTx":           {function: "SqlBeginTx", returns: generatedStdlibReturnValueError},
	"SqlClose":             {function: "SqlClose", returns: generatedStdlibReturnError},
	"SqlCommit":            {function: "SqlCommit", returns: generatedStdlibReturnError},
	"SqlCreateConnection":  {function: "SqlCreateConnection", returns: generatedStdlibReturnValueError},
	"SqlExtractParams":     {function: "SqlExtractParams", returns: generatedStdlibReturnDirect},
	"SqlRollback":          {function: "SqlRollback", returns: generatedStdlibReturnError},
	"StrToDynamic":         {function: "StrToDynamic", returns: generatedStdlibReturnDirect},
	"VoidToDynamic":        {function: "VoidToDynamic", returns: generatedStdlibReturnDirect},
}

func (l *lowerer) lowerGeneratedStdlibExtern(binding string, args []ast.Expr, stmts []ast.Stmt, returnTypeID air.TypeID) (loweredExpr, bool, error) {
	lowering, ok := generatedStdlibExternLowerings[binding]
	if !ok {
		return loweredExpr{}, false, nil
	}
	call := &ast.CallExpr{Fun: l.qualified("stdlibffi", "github.com/akonwi/ard/std_lib/ffi", lowering.function), Args: args}
	switch lowering.returns {
	case generatedStdlibReturnError:
		wrapped, err := l.wrapErrorCall(returnTypeID, call)
		if err != nil {
			return loweredExpr{}, true, err
		}
		wrapped.stmts = append(stmts, wrapped.stmts...)
		return wrapped, true, nil
	case generatedStdlibReturnValueError:
		wrapped, err := l.wrapValueErrorCall(returnTypeID, call)
		if err != nil {
			return loweredExpr{}, true, err
		}
		wrapped.stmts = append(stmts, wrapped.stmts...)
		return wrapped, true, nil
	case generatedStdlibReturnResult:
		wrapped, err := l.wrapStdlibResultCall(returnTypeID, call)
		if err != nil {
			return loweredExpr{}, true, err
		}
		wrapped.stmts = append(stmts, wrapped.stmts...)
		return wrapped, true, nil
	default:
		return loweredExpr{stmts: stmts, expr: call}, true, nil
	}
}
