// Code generated by generate.go; DO NOT EDIT.

package vm

import (
	"fmt"

	"github.com/akonwi/ard/checker"
	"github.com/akonwi/ard/ffi"
	"github.com/akonwi/ard/runtime"
)

func _ffi_Base64Encode(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	var arg1 *bool
	if !args[1].IsNone() {
		_v1 := args[1].AsBool()
		arg1 = &_v1
	}
	result := ffi.Base64Encode(arg0, arg1)
	return runtime.MakeStr(result)
}

func _ffi_Base64Decode(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	var arg1 *bool
	if !args[1].IsNone() {
		_v1 := args[1].AsBool()
		arg1 = &_v1
	}
	result, err := ffi.Base64Decode(arg0, arg1)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeStr(result))
}

func _ffi_Base64EncodeURL(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	var arg1 *bool
	if !args[1].IsNone() {
		_v1 := args[1].AsBool()
		arg1 = &_v1
	}
	result := ffi.Base64EncodeURL(arg0, arg1)
	return runtime.MakeStr(result)
}

func _ffi_Base64DecodeURL(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	var arg1 *bool
	if !args[1].IsNone() {
		_v1 := args[1].AsBool()
		arg1 = &_v1
	}
	result, err := ffi.Base64DecodeURL(arg0, arg1)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeStr(result))
}

func _ffi_CryptoMd5(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result := ffi.CryptoMd5(arg0)
	return runtime.MakeStr(result)
}

func _ffi_CryptoSha256(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result := ffi.CryptoSha256(arg0)
	return runtime.MakeStr(result)
}

func _ffi_CryptoSha512(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result := ffi.CryptoSha512(arg0)
	return runtime.MakeStr(result)
}

func _ffi_CryptoHashPassword(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	var arg1 *int
	if !args[1].IsNone() {
		_v1 := args[1].AsInt()
		arg1 = &_v1
	}
	result, err := ffi.CryptoHashPassword(arg0, arg1)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeStr(result))
}

func _ffi_CryptoVerifyPassword(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	arg1 := args[1].AsString()
	result, err := ffi.CryptoVerifyPassword(arg0, arg1)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeBool(result))
}

func _ffi_CryptoScryptHash(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	var arg1 *string
	if !args[1].IsNone() {
		_v1 := args[1].AsString()
		arg1 = &_v1
	}
	var arg2 *int
	if !args[2].IsNone() {
		_v2 := args[2].AsInt()
		arg2 = &_v2
	}
	var arg3 *int
	if !args[3].IsNone() {
		_v3 := args[3].AsInt()
		arg3 = &_v3
	}
	var arg4 *int
	if !args[4].IsNone() {
		_v4 := args[4].AsInt()
		arg4 = &_v4
	}
	var arg5 *int
	if !args[5].IsNone() {
		_v5 := args[5].AsInt()
		arg5 = &_v5
	}
	result, err := ffi.CryptoScryptHash(arg0, arg1, arg2, arg3, arg4, arg5)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeStr(result))
}

func _ffi_CryptoScryptVerify(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	arg1 := args[1].AsString()
	var arg2 *int
	if !args[2].IsNone() {
		_v2 := args[2].AsInt()
		arg2 = &_v2
	}
	var arg3 *int
	if !args[3].IsNone() {
		_v3 := args[3].AsInt()
		arg3 = &_v3
	}
	var arg4 *int
	if !args[4].IsNone() {
		_v4 := args[4].AsInt()
		arg4 = &_v4
	}
	var arg5 *int
	if !args[5].IsNone() {
		_v5 := args[5].AsInt()
		arg5 = &_v5
	}
	result, err := ffi.CryptoScryptVerify(arg0, arg1, arg2, arg3, arg4, arg5)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeBool(result))
}

func _ffi_CryptoUUID(args []*runtime.Object) *runtime.Object {
	result := ffi.CryptoUUID()
	return runtime.MakeStr(result)
}

func _ffi_ListToDynamic(args []*runtime.Object) *runtime.Object {
	_sl0 := args[0].AsList()
	arg0 := make([]any, len(_sl0))
	for _i0, _e0 := range _sl0 {
		arg0[_i0] = _e0.Raw()
	}
	result := ffi.ListToDynamic(arg0)
	return runtime.MakeDynamic(result)
}

func _ffi_MapToDynamic(args []*runtime.Object) *runtime.Object {
	_rawMap0 := args[0].AsMap()
	arg0 := make(map[string]any, len(_rawMap0))
	for _k0, _v0 := range _rawMap0 {
		arg0[_k0] = _v0.Raw()
	}
	result := ffi.MapToDynamic(arg0)
	return runtime.MakeDynamic(result)
}

func _ffi_JsonToDynamic(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result, err := ffi.JsonToDynamic(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeDynamic(result))
}

func _ffi_IsNil(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	result := ffi.IsNil(arg0)
	return runtime.MakeBool(result)
}

func _ffi_FS_Exists(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result := ffi.FS_Exists(arg0)
	return runtime.MakeBool(result)
}

func _ffi_FS_CreateFile(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result, err := ffi.FS_CreateFile(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeBool(result))
}

func _ffi_FS_WriteFile(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	arg1 := args[1].AsString()
	err := ffi.FS_WriteFile(arg0, arg1)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.Void())
}

func _ffi_FS_AppendFile(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	arg1 := args[1].AsString()
	err := ffi.FS_AppendFile(arg0, arg1)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.Void())
}

func _ffi_FS_ReadFile(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result, err := ffi.FS_ReadFile(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeStr(result))
}

func _ffi_FS_DeleteFile(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	err := ffi.FS_DeleteFile(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.Void())
}

func _ffi_FS_IsFile(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result := ffi.FS_IsFile(arg0)
	return runtime.MakeBool(result)
}

func _ffi_FS_IsDir(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result := ffi.FS_IsDir(arg0)
	return runtime.MakeBool(result)
}

func _ffi_FS_Copy(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	arg1 := args[1].AsString()
	err := ffi.FS_Copy(arg0, arg1)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.Void())
}

func _ffi_FS_Rename(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	arg1 := args[1].AsString()
	err := ffi.FS_Rename(arg0, arg1)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.Void())
}

func _ffi_FS_Cwd(args []*runtime.Object) *runtime.Object {
	result, err := ffi.FS_Cwd()
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeStr(result))
}

func _ffi_FS_Abs(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result, err := ffi.FS_Abs(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeStr(result))
}

func _ffi_FS_CreateDir(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	err := ffi.FS_CreateDir(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.Void())
}

func _ffi_FS_DeleteDir(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	err := ffi.FS_DeleteDir(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.Void())
}

func _ffi_FS_ListDir(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result, err := ffi.FS_ListDir(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	_map := runtime.MakeMap(checker.Str, checker.Bool)
	for _k, _v := range result {
		_map.Map_Set(runtime.MakeStr(_k), runtime.MakeBool(_v))
	}
	return runtime.MakeOk(_map)
}

func _ffi_HexEncode(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result := ffi.HexEncode(arg0)
	return runtime.MakeStr(result)
}

func _ffi_HexDecode(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result, err := ffi.HexDecode(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeStr(result))
}

func _ffi_GetReqPath(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	result := ffi.GetReqPath(arg0)
	return runtime.MakeStr(result)
}

func _ffi_GetPathValue(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	arg1 := args[1].AsString()
	result := ffi.GetPathValue(arg0, arg1)
	return runtime.MakeStr(result)
}

func _ffi_GetQueryParam(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	arg1 := args[1].AsString()
	result := ffi.GetQueryParam(arg0, arg1)
	return runtime.MakeStr(result)
}

func _ffi_HTTP_Do(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	arg1 := args[1].AsString()
	arg2 := args[2].Raw()
	_rawMap3 := args[3].AsMap()
	arg3 := make(map[string]string, len(_rawMap3))
	for _k3, _v3 := range _rawMap3 {
		arg3[_k3] = _v3.AsString()
	}
	var arg4 *int
	if !args[4].IsNone() {
		_v4 := args[4].AsInt()
		arg4 = &_v4
	}
	result, err := ffi.HTTP_Do(arg0, arg1, arg2, arg3, arg4)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeDynamic(result))
}

func _ffi_HTTP_ResponseStatus(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	result := ffi.HTTP_ResponseStatus(arg0)
	return runtime.MakeInt(result)
}

func _ffi_HTTP_ResponseHeader(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	arg1 := args[1].AsString()
	result := ffi.HTTP_ResponseHeader(arg0, arg1)
	if result == nil {
		return runtime.MakeNone(checker.Str)
	}
	return runtime.MakeNone(checker.Str).ToSome(*result)
}

func _ffi_HTTP_ResponseHeaders(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	result := ffi.HTTP_ResponseHeaders(arg0)
	_map := runtime.MakeMap(checker.Str, checker.Str)
	for _k, _v := range result {
		_map.Map_Set(runtime.MakeStr(_k), runtime.MakeStr(_v))
	}
	return _map
}

func _ffi_HTTP_ResponseBody(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	result, err := ffi.HTTP_ResponseBody(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeStr(result))
}

func _ffi_HTTP_ResponseClose(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	ffi.HTTP_ResponseClose(arg0)
	return runtime.Void()
}

func _ffi_JsonEncode(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	result, err := ffi.JsonEncode(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeStr(result))
}

func _ffi_FloatFromStr(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result := ffi.FloatFromStr(arg0)
	if result == nil {
		return runtime.MakeNone(checker.Float)
	}
	return runtime.MakeNone(checker.Float).ToSome(*result)
}

func _ffi_FloatFromInt(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsInt()
	result := ffi.FloatFromInt(arg0)
	return runtime.MakeFloat(result)
}

func _ffi_FloatFloor(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsFloat()
	result := ffi.FloatFloor(arg0)
	return runtime.MakeFloat(result)
}

func _ffi_IntFromStr(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result := ffi.IntFromStr(arg0)
	if result == nil {
		return runtime.MakeNone(checker.Int)
	}
	return runtime.MakeNone(checker.Int).ToSome(*result)
}

func _ffi_OsArgs(args []*runtime.Object) *runtime.Object {
	result := ffi.OsArgs()
	_items := make([]*runtime.Object, len(result))
	for _i, _v := range result {
		_items[_i] = runtime.MakeStr(_v)
	}
	return runtime.MakeList(checker.Str, _items...)
}

func _ffi_Print(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	ffi.Print(arg0)
	return runtime.Void()
}

func _ffi_ReadLine(args []*runtime.Object) *runtime.Object {
	result, err := ffi.ReadLine()
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeStr(result))
}

func _ffi_PanicWithMessage(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	ffi.PanicWithMessage(arg0)
	return runtime.Void()
}

func _ffi_EnvGet(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result := ffi.EnvGet(arg0)
	if result == nil {
		return runtime.MakeNone(checker.Str)
	}
	return runtime.MakeNone(checker.Str).ToSome(*result)
}

func _ffi_GetTodayString(args []*runtime.Object) *runtime.Object {
	result := ffi.GetTodayString()
	return runtime.MakeStr(result)
}

func _ffi_Now(args []*runtime.Object) *runtime.Object {
	result := ffi.Now()
	return runtime.MakeInt(result)
}

func _ffi_Sleep(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsInt()
	ffi.Sleep(arg0)
	return runtime.Void()
}

func _ffi_WaitFor(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	ffi.WaitFor(arg0)
	return runtime.Void()
}

func _ffi_SqlCreateConnection(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result, err := ffi.SqlCreateConnection(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeDynamic(result))
}

func _ffi_SqlClose(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	err := ffi.SqlClose(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.Void())
}

func _ffi_SqlExtractParams(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].AsString()
	result := ffi.SqlExtractParams(arg0)
	_items := make([]*runtime.Object, len(result))
	for _i, _v := range result {
		_items[_i] = runtime.MakeStr(_v)
	}
	return runtime.MakeList(checker.Str, _items...)
}

func _ffi_SqlQuery(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	arg1 := args[1].AsString()
	_sl2 := args[2].AsList()
	arg2 := make([]any, len(_sl2))
	for _i2, _e2 := range _sl2 {
		arg2[_i2] = _e2.Raw()
	}
	result, err := ffi.SqlQuery(arg0, arg1, arg2)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	_items := make([]*runtime.Object, len(result))
	for _i, _v := range result {
		_items[_i] = runtime.MakeDynamic(_v)
	}
	return runtime.MakeOk(runtime.MakeList(checker.Dynamic, _items...))
}

func _ffi_SqlExecute(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	arg1 := args[1].AsString()
	_sl2 := args[2].AsList()
	arg2 := make([]any, len(_sl2))
	for _i2, _e2 := range _sl2 {
		arg2[_i2] = _e2.Raw()
	}
	err := ffi.SqlExecute(arg0, arg1, arg2)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.Void())
}

func _ffi_SqlBeginTx(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	result, err := ffi.SqlBeginTx(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.MakeDynamic(result))
}

func _ffi_SqlCommit(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	err := ffi.SqlCommit(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.Void())
}

func _ffi_SqlRollback(args []*runtime.Object) *runtime.Object {
	arg0 := args[0].Raw()
	err := ffi.SqlRollback(arg0)
	if err != nil {
		return runtime.MakeErr(runtime.MakeStr(err.Error()))
	}
	return runtime.MakeOk(runtime.Void())
}

// RegisterGeneratedFFIFunctions registers all discovered FFI functions
func (r *RuntimeFFIRegistry) RegisterGeneratedFFIFunctions() error {
	if err := r.Register("Base64Encode", _ffi_Base64Encode); err != nil {
		return fmt.Errorf("failed to register Base64Encode: %w", err)
	}
	if err := r.Register("Base64Decode", _ffi_Base64Decode); err != nil {
		return fmt.Errorf("failed to register Base64Decode: %w", err)
	}
	if err := r.Register("Base64EncodeURL", _ffi_Base64EncodeURL); err != nil {
		return fmt.Errorf("failed to register Base64EncodeURL: %w", err)
	}
	if err := r.Register("Base64DecodeURL", _ffi_Base64DecodeURL); err != nil {
		return fmt.Errorf("failed to register Base64DecodeURL: %w", err)
	}
	if err := r.Register("CryptoMd5", _ffi_CryptoMd5); err != nil {
		return fmt.Errorf("failed to register CryptoMd5: %w", err)
	}
	if err := r.Register("CryptoSha256", _ffi_CryptoSha256); err != nil {
		return fmt.Errorf("failed to register CryptoSha256: %w", err)
	}
	if err := r.Register("CryptoSha512", _ffi_CryptoSha512); err != nil {
		return fmt.Errorf("failed to register CryptoSha512: %w", err)
	}
	if err := r.Register("CryptoHashPassword", _ffi_CryptoHashPassword); err != nil {
		return fmt.Errorf("failed to register CryptoHashPassword: %w", err)
	}
	if err := r.Register("CryptoVerifyPassword", _ffi_CryptoVerifyPassword); err != nil {
		return fmt.Errorf("failed to register CryptoVerifyPassword: %w", err)
	}
	if err := r.Register("CryptoScryptHash", _ffi_CryptoScryptHash); err != nil {
		return fmt.Errorf("failed to register CryptoScryptHash: %w", err)
	}
	if err := r.Register("CryptoScryptVerify", _ffi_CryptoScryptVerify); err != nil {
		return fmt.Errorf("failed to register CryptoScryptVerify: %w", err)
	}
	if err := r.Register("CryptoUUID", _ffi_CryptoUUID); err != nil {
		return fmt.Errorf("failed to register CryptoUUID: %w", err)
	}
	if err := r.Register("ListToDynamic", _ffi_ListToDynamic); err != nil {
		return fmt.Errorf("failed to register ListToDynamic: %w", err)
	}
	if err := r.Register("MapToDynamic", _ffi_MapToDynamic); err != nil {
		return fmt.Errorf("failed to register MapToDynamic: %w", err)
	}
	if err := r.Register("JsonToDynamic", _ffi_JsonToDynamic); err != nil {
		return fmt.Errorf("failed to register JsonToDynamic: %w", err)
	}
	if err := r.Register("DecodeString", ffi.DecodeString); err != nil {
		return fmt.Errorf("failed to register DecodeString: %w", err)
	}
	if err := r.Register("DecodeInt", ffi.DecodeInt); err != nil {
		return fmt.Errorf("failed to register DecodeInt: %w", err)
	}
	if err := r.Register("DecodeStringErrors", ffi.DecodeStringErrors); err != nil {
		return fmt.Errorf("failed to register DecodeStringErrors: %w", err)
	}
	if err := r.Register("DecodeIntErrors", ffi.DecodeIntErrors); err != nil {
		return fmt.Errorf("failed to register DecodeIntErrors: %w", err)
	}
	if err := r.Register("DecodeStringIntMapErrors", ffi.DecodeStringIntMapErrors); err != nil {
		return fmt.Errorf("failed to register DecodeStringIntMapErrors: %w", err)
	}
	if err := r.Register("DecodeIntListErrors", ffi.DecodeIntListErrors); err != nil {
		return fmt.Errorf("failed to register DecodeIntListErrors: %w", err)
	}
	if err := r.Register("DecodeFloat", ffi.DecodeFloat); err != nil {
		return fmt.Errorf("failed to register DecodeFloat: %w", err)
	}
	if err := r.Register("DecodeBool", ffi.DecodeBool); err != nil {
		return fmt.Errorf("failed to register DecodeBool: %w", err)
	}
	if err := r.Register("IsNil", _ffi_IsNil); err != nil {
		return fmt.Errorf("failed to register IsNil: %w", err)
	}
	if err := r.Register("DynamicToList", ffi.DynamicToList); err != nil {
		return fmt.Errorf("failed to register DynamicToList: %w", err)
	}
	if err := r.Register("DynamicToMap", ffi.DynamicToMap); err != nil {
		return fmt.Errorf("failed to register DynamicToMap: %w", err)
	}
	if err := r.Register("DynamicToStringMap", ffi.DynamicToStringMap); err != nil {
		return fmt.Errorf("failed to register DynamicToStringMap: %w", err)
	}
	if err := r.Register("ExtractField", ffi.ExtractField); err != nil {
		return fmt.Errorf("failed to register ExtractField: %w", err)
	}
	if err := r.Register("FS_Exists", _ffi_FS_Exists); err != nil {
		return fmt.Errorf("failed to register FS_Exists: %w", err)
	}
	if err := r.Register("FS_CreateFile", _ffi_FS_CreateFile); err != nil {
		return fmt.Errorf("failed to register FS_CreateFile: %w", err)
	}
	if err := r.Register("FS_WriteFile", _ffi_FS_WriteFile); err != nil {
		return fmt.Errorf("failed to register FS_WriteFile: %w", err)
	}
	if err := r.Register("FS_AppendFile", _ffi_FS_AppendFile); err != nil {
		return fmt.Errorf("failed to register FS_AppendFile: %w", err)
	}
	if err := r.Register("FS_ReadFile", _ffi_FS_ReadFile); err != nil {
		return fmt.Errorf("failed to register FS_ReadFile: %w", err)
	}
	if err := r.Register("FS_DeleteFile", _ffi_FS_DeleteFile); err != nil {
		return fmt.Errorf("failed to register FS_DeleteFile: %w", err)
	}
	if err := r.Register("FS_IsFile", _ffi_FS_IsFile); err != nil {
		return fmt.Errorf("failed to register FS_IsFile: %w", err)
	}
	if err := r.Register("FS_IsDir", _ffi_FS_IsDir); err != nil {
		return fmt.Errorf("failed to register FS_IsDir: %w", err)
	}
	if err := r.Register("FS_Copy", _ffi_FS_Copy); err != nil {
		return fmt.Errorf("failed to register FS_Copy: %w", err)
	}
	if err := r.Register("FS_Rename", _ffi_FS_Rename); err != nil {
		return fmt.Errorf("failed to register FS_Rename: %w", err)
	}
	if err := r.Register("FS_Cwd", _ffi_FS_Cwd); err != nil {
		return fmt.Errorf("failed to register FS_Cwd: %w", err)
	}
	if err := r.Register("FS_Abs", _ffi_FS_Abs); err != nil {
		return fmt.Errorf("failed to register FS_Abs: %w", err)
	}
	if err := r.Register("FS_CreateDir", _ffi_FS_CreateDir); err != nil {
		return fmt.Errorf("failed to register FS_CreateDir: %w", err)
	}
	if err := r.Register("FS_DeleteDir", _ffi_FS_DeleteDir); err != nil {
		return fmt.Errorf("failed to register FS_DeleteDir: %w", err)
	}
	if err := r.Register("FS_ListDir", _ffi_FS_ListDir); err != nil {
		return fmt.Errorf("failed to register FS_ListDir: %w", err)
	}
	if err := r.Register("HexEncode", _ffi_HexEncode); err != nil {
		return fmt.Errorf("failed to register HexEncode: %w", err)
	}
	if err := r.Register("HexDecode", _ffi_HexDecode); err != nil {
		return fmt.Errorf("failed to register HexDecode: %w", err)
	}
	if err := r.Register("GetReqPath", _ffi_GetReqPath); err != nil {
		return fmt.Errorf("failed to register GetReqPath: %w", err)
	}
	if err := r.Register("GetPathValue", _ffi_GetPathValue); err != nil {
		return fmt.Errorf("failed to register GetPathValue: %w", err)
	}
	if err := r.Register("GetQueryParam", _ffi_GetQueryParam); err != nil {
		return fmt.Errorf("failed to register GetQueryParam: %w", err)
	}
	if err := r.Register("HTTP_Do", _ffi_HTTP_Do); err != nil {
		return fmt.Errorf("failed to register HTTP_Do: %w", err)
	}
	if err := r.Register("HTTP_ResponseStatus", _ffi_HTTP_ResponseStatus); err != nil {
		return fmt.Errorf("failed to register HTTP_ResponseStatus: %w", err)
	}
	if err := r.Register("HTTP_ResponseHeader", _ffi_HTTP_ResponseHeader); err != nil {
		return fmt.Errorf("failed to register HTTP_ResponseHeader: %w", err)
	}
	if err := r.Register("HTTP_ResponseHeaders", _ffi_HTTP_ResponseHeaders); err != nil {
		return fmt.Errorf("failed to register HTTP_ResponseHeaders: %w", err)
	}
	if err := r.Register("HTTP_ResponseBody", _ffi_HTTP_ResponseBody); err != nil {
		return fmt.Errorf("failed to register HTTP_ResponseBody: %w", err)
	}
	if err := r.Register("HTTP_ResponseClose", _ffi_HTTP_ResponseClose); err != nil {
		return fmt.Errorf("failed to register HTTP_ResponseClose: %w", err)
	}
	if err := r.Register("HTTP_Serve", ffi.HTTP_Serve); err != nil {
		return fmt.Errorf("failed to register HTTP_Serve: %w", err)
	}
	if err := r.Register("JsonEncode", _ffi_JsonEncode); err != nil {
		return fmt.Errorf("failed to register JsonEncode: %w", err)
	}
	if err := r.Register("FloatFromStr", _ffi_FloatFromStr); err != nil {
		return fmt.Errorf("failed to register FloatFromStr: %w", err)
	}
	if err := r.Register("FloatFromInt", _ffi_FloatFromInt); err != nil {
		return fmt.Errorf("failed to register FloatFromInt: %w", err)
	}
	if err := r.Register("FloatFloor", _ffi_FloatFloor); err != nil {
		return fmt.Errorf("failed to register FloatFloor: %w", err)
	}
	if err := r.Register("IntFromStr", _ffi_IntFromStr); err != nil {
		return fmt.Errorf("failed to register IntFromStr: %w", err)
	}
	if err := r.Register("OsArgs", _ffi_OsArgs); err != nil {
		return fmt.Errorf("failed to register OsArgs: %w", err)
	}
	if err := r.Register("Print", _ffi_Print); err != nil {
		return fmt.Errorf("failed to register Print: %w", err)
	}
	if err := r.Register("ReadLine", _ffi_ReadLine); err != nil {
		return fmt.Errorf("failed to register ReadLine: %w", err)
	}
	if err := r.Register("PanicWithMessage", _ffi_PanicWithMessage); err != nil {
		return fmt.Errorf("failed to register PanicWithMessage: %w", err)
	}
	if err := r.Register("EnvGet", _ffi_EnvGet); err != nil {
		return fmt.Errorf("failed to register EnvGet: %w", err)
	}
	if err := r.Register("GetTodayString", _ffi_GetTodayString); err != nil {
		return fmt.Errorf("failed to register GetTodayString: %w", err)
	}
	if err := r.Register("Now", _ffi_Now); err != nil {
		return fmt.Errorf("failed to register Now: %w", err)
	}
	if err := r.Register("Sleep", _ffi_Sleep); err != nil {
		return fmt.Errorf("failed to register Sleep: %w", err)
	}
	if err := r.Register("WaitFor", _ffi_WaitFor); err != nil {
		return fmt.Errorf("failed to register WaitFor: %w", err)
	}
	if err := r.Register("GetResult", ffi.GetResult); err != nil {
		return fmt.Errorf("failed to register GetResult: %w", err)
	}
	if err := r.Register("SqlCreateConnection", _ffi_SqlCreateConnection); err != nil {
		return fmt.Errorf("failed to register SqlCreateConnection: %w", err)
	}
	if err := r.Register("SqlClose", _ffi_SqlClose); err != nil {
		return fmt.Errorf("failed to register SqlClose: %w", err)
	}
	if err := r.Register("SqlExtractParams", _ffi_SqlExtractParams); err != nil {
		return fmt.Errorf("failed to register SqlExtractParams: %w", err)
	}
	if err := r.Register("SqlQuery", _ffi_SqlQuery); err != nil {
		return fmt.Errorf("failed to register SqlQuery: %w", err)
	}
	if err := r.Register("SqlExecute", _ffi_SqlExecute); err != nil {
		return fmt.Errorf("failed to register SqlExecute: %w", err)
	}
	if err := r.Register("SqlBeginTx", _ffi_SqlBeginTx); err != nil {
		return fmt.Errorf("failed to register SqlBeginTx: %w", err)
	}
	if err := r.Register("SqlCommit", _ffi_SqlCommit); err != nil {
		return fmt.Errorf("failed to register SqlCommit: %w", err)
	}
	if err := r.Register("SqlRollback", _ffi_SqlRollback); err != nil {
		return fmt.Errorf("failed to register SqlRollback: %w", err)
	}

	return nil
}
