id = "ard"
name = "Ard"
version = "0.0.1"
schema_version = 1
authors = ["Akonwi Ngoh <akonwi@gmail.com>"]
description = "Language support for Ard"
repository = "https://github.com/akonwi/ard"

[grammars.ard]
repository = "file:///Users/akonwi/Developer/agent/ard/tree-sitter-ard"
commit = "a4a940fba5f985a0ed804cef58c00c2161bd5af9"

[language_servers.ard-lsp]
name = "Ard Language Server"
languages = ["Ard"]
