id = "ard"
name = "Ard"
version = "0.0.1"
schema_version = 1
authors = ["Akonwi Ngoh <akonwi@gmail.com>"]
description = "Language support for Ard"
repository = "https://github.com/akonwi/ard"

[grammars.ard]
repository = "file:///Users/akonwi/Developer/agent/ard/tree-sitter-ard"
commit = "c8018f97d43ee6640cac50f3bb33db99fbf6d713"

[language_servers.ard-lsp]
name = "Ard Language Server"
languages = ["Ard"]
