id = "ard"
name = "Ard"
version = "0.0.1"
schema_version = 1
authors = ["Akonwi Ngoh <akonwi@gmail.com>"]
description = "Language support for Ard"
repository = "https://github.com/akonwi/ard"

[grammars.ard]
repository = "file:///Users/akonwi/Developer/agent/ard/tree-sitter-ard"
commit = "112e646b6d5b91b444cb373d51a883c2bfcc8087"

[language_servers.ard-lsp]
name = "Ard Language Server"
languages = ["Ard"]
