// Code generated by generate.go; DO NOT EDIT.

package vm

import (
	"fmt"

	"github.com/akonwi/ard/ffi"
)

// RegisterGeneratedFFIFunctions registers all discovered FFI functions
func (r *RuntimeFFIRegistry) RegisterGeneratedFFIFunctions() error {
	if err := r.Register("CryptoMd5", ffi.CryptoMd5); err != nil {
		return fmt.Errorf("failed to register CryptoMd5: %w", err)
	}
	if err := r.Register("CryptoSha256", ffi.CryptoSha256); err != nil {
		return fmt.Errorf("failed to register CryptoSha256: %w", err)
	}
	if err := r.Register("CryptoSha512", ffi.CryptoSha512); err != nil {
		return fmt.Errorf("failed to register CryptoSha512: %w", err)
	}
	if err := r.Register("CryptoHashPassword", ffi.CryptoHashPassword); err != nil {
		return fmt.Errorf("failed to register CryptoHashPassword: %w", err)
	}
	if err := r.Register("CryptoVerifyPassword", ffi.CryptoVerifyPassword); err != nil {
		return fmt.Errorf("failed to register CryptoVerifyPassword: %w", err)
	}
	if err := r.Register("CryptoUUID", ffi.CryptoUUID); err != nil {
		return fmt.Errorf("failed to register CryptoUUID: %w", err)
	}
	if err := r.Register("StrToDynamic", ffi.StrToDynamic); err != nil {
		return fmt.Errorf("failed to register StrToDynamic: %w", err)
	}
	if err := r.Register("IntToDynamic", ffi.IntToDynamic); err != nil {
		return fmt.Errorf("failed to register IntToDynamic: %w", err)
	}
	if err := r.Register("FloatToDynamic", ffi.FloatToDynamic); err != nil {
		return fmt.Errorf("failed to register FloatToDynamic: %w", err)
	}
	if err := r.Register("BoolToDynamic", ffi.BoolToDynamic); err != nil {
		return fmt.Errorf("failed to register BoolToDynamic: %w", err)
	}
	if err := r.Register("VoidToDynamic", ffi.VoidToDynamic); err != nil {
		return fmt.Errorf("failed to register VoidToDynamic: %w", err)
	}
	if err := r.Register("ListToDynamic", ffi.ListToDynamic); err != nil {
		return fmt.Errorf("failed to register ListToDynamic: %w", err)
	}
	if err := r.Register("MapToDynamic", ffi.MapToDynamic); err != nil {
		return fmt.Errorf("failed to register MapToDynamic: %w", err)
	}
	if err := r.Register("JsonToDynamic", ffi.JsonToDynamic); err != nil {
		return fmt.Errorf("failed to register JsonToDynamic: %w", err)
	}
	if err := r.Register("DecodeString", ffi.DecodeString); err != nil {
		return fmt.Errorf("failed to register DecodeString: %w", err)
	}
	if err := r.Register("DecodeInt", ffi.DecodeInt); err != nil {
		return fmt.Errorf("failed to register DecodeInt: %w", err)
	}
	if err := r.Register("DecodeFloat", ffi.DecodeFloat); err != nil {
		return fmt.Errorf("failed to register DecodeFloat: %w", err)
	}
	if err := r.Register("DecodeBool", ffi.DecodeBool); err != nil {
		return fmt.Errorf("failed to register DecodeBool: %w", err)
	}
	if err := r.Register("IsNil", ffi.IsNil); err != nil {
		return fmt.Errorf("failed to register IsNil: %w", err)
	}
	if err := r.Register("DynamicToList", ffi.DynamicToList); err != nil {
		return fmt.Errorf("failed to register DynamicToList: %w", err)
	}
	if err := r.Register("DynamicToMap", ffi.DynamicToMap); err != nil {
		return fmt.Errorf("failed to register DynamicToMap: %w", err)
	}
	if err := r.Register("ExtractField", ffi.ExtractField); err != nil {
		return fmt.Errorf("failed to register ExtractField: %w", err)
	}
	if err := r.Register("FS_Exists", ffi.FS_Exists); err != nil {
		return fmt.Errorf("failed to register FS_Exists: %w", err)
	}
	if err := r.Register("FS_CreateFile", ffi.FS_CreateFile); err != nil {
		return fmt.Errorf("failed to register FS_CreateFile: %w", err)
	}
	if err := r.Register("FS_WriteFile", ffi.FS_WriteFile); err != nil {
		return fmt.Errorf("failed to register FS_WriteFile: %w", err)
	}
	if err := r.Register("FS_AppendFile", ffi.FS_AppendFile); err != nil {
		return fmt.Errorf("failed to register FS_AppendFile: %w", err)
	}
	if err := r.Register("FS_ReadFile", ffi.FS_ReadFile); err != nil {
		return fmt.Errorf("failed to register FS_ReadFile: %w", err)
	}
	if err := r.Register("FS_DeleteFile", ffi.FS_DeleteFile); err != nil {
		return fmt.Errorf("failed to register FS_DeleteFile: %w", err)
	}
	if err := r.Register("FS_IsFile", ffi.FS_IsFile); err != nil {
		return fmt.Errorf("failed to register FS_IsFile: %w", err)
	}
	if err := r.Register("FS_IsDir", ffi.FS_IsDir); err != nil {
		return fmt.Errorf("failed to register FS_IsDir: %w", err)
	}
	if err := r.Register("FS_ListDir", ffi.FS_ListDir); err != nil {
		return fmt.Errorf("failed to register FS_ListDir: %w", err)
	}
	if err := r.Register("GetReqPath", ffi.GetReqPath); err != nil {
		return fmt.Errorf("failed to register GetReqPath: %w", err)
	}
	if err := r.Register("GetPathValue", ffi.GetPathValue); err != nil {
		return fmt.Errorf("failed to register GetPathValue: %w", err)
	}
	if err := r.Register("GetQueryParam", ffi.GetQueryParam); err != nil {
		return fmt.Errorf("failed to register GetQueryParam: %w", err)
	}
	if err := r.Register("HTTP_Send", ffi.HTTP_Send); err != nil {
		return fmt.Errorf("failed to register HTTP_Send: %w", err)
	}
	if err := r.Register("HTTP_Serve", ffi.HTTP_Serve); err != nil {
		return fmt.Errorf("failed to register HTTP_Serve: %w", err)
	}
	if err := r.Register("JsonEncode", ffi.JsonEncode); err != nil {
		return fmt.Errorf("failed to register JsonEncode: %w", err)
	}
	if err := r.Register("FloatFromStr", ffi.FloatFromStr); err != nil {
		return fmt.Errorf("failed to register FloatFromStr: %w", err)
	}
	if err := r.Register("FloatFromInt", ffi.FloatFromInt); err != nil {
		return fmt.Errorf("failed to register FloatFromInt: %w", err)
	}
	if err := r.Register("FloatFloor", ffi.FloatFloor); err != nil {
		return fmt.Errorf("failed to register FloatFloor: %w", err)
	}
	if err := r.Register("IntFromStr", ffi.IntFromStr); err != nil {
		return fmt.Errorf("failed to register IntFromStr: %w", err)
	}
	if err := r.Register("NewList", ffi.NewList); err != nil {
		return fmt.Errorf("failed to register NewList: %w", err)
	}
	if err := r.Register("OsArgs", ffi.OsArgs); err != nil {
		return fmt.Errorf("failed to register OsArgs: %w", err)
	}
	if err := r.Register("Print", ffi.Print); err != nil {
		return fmt.Errorf("failed to register Print: %w", err)
	}
	if err := r.Register("ReadLine", ffi.ReadLine); err != nil {
		return fmt.Errorf("failed to register ReadLine: %w", err)
	}
	if err := r.Register("PanicWithMessage", ffi.PanicWithMessage); err != nil {
		return fmt.Errorf("failed to register PanicWithMessage: %w", err)
	}
	if err := r.Register("EnvGet", ffi.EnvGet); err != nil {
		return fmt.Errorf("failed to register EnvGet: %w", err)
	}
	if err := r.Register("GetTodayString", ffi.GetTodayString); err != nil {
		return fmt.Errorf("failed to register GetTodayString: %w", err)
	}
	if err := r.Register("Now", ffi.Now); err != nil {
		return fmt.Errorf("failed to register Now: %w", err)
	}
	if err := r.Register("Sleep", ffi.Sleep); err != nil {
		return fmt.Errorf("failed to register Sleep: %w", err)
	}
	if err := r.Register("WaitFor", ffi.WaitFor); err != nil {
		return fmt.Errorf("failed to register WaitFor: %w", err)
	}
	if err := r.Register("Join", ffi.Join); err != nil {
		return fmt.Errorf("failed to register Join: %w", err)
	}
	if err := r.Register("SqlCreateConnection", ffi.SqlCreateConnection); err != nil {
		return fmt.Errorf("failed to register SqlCreateConnection: %w", err)
	}
	if err := r.Register("SqlClose", ffi.SqlClose); err != nil {
		return fmt.Errorf("failed to register SqlClose: %w", err)
	}
	if err := r.Register("SqlExtractParams", ffi.SqlExtractParams); err != nil {
		return fmt.Errorf("failed to register SqlExtractParams: %w", err)
	}
	if err := r.Register("SqlQuery", ffi.SqlQuery); err != nil {
		return fmt.Errorf("failed to register SqlQuery: %w", err)
	}
	if err := r.Register("SqlExecute", ffi.SqlExecute); err != nil {
		return fmt.Errorf("failed to register SqlExecute: %w", err)
	}
	if err := r.Register("SqlBeginTx", ffi.SqlBeginTx); err != nil {
		return fmt.Errorf("failed to register SqlBeginTx: %w", err)
	}
	if err := r.Register("SqlCommit", ffi.SqlCommit); err != nil {
		return fmt.Errorf("failed to register SqlCommit: %w", err)
	}
	if err := r.Register("SqlRollback", ffi.SqlRollback); err != nil {
		return fmt.Errorf("failed to register SqlRollback: %w", err)
	}

	return nil
}
