use ard/io

struct Student {
  name: Str,
  grade: Num
}

let students: [Student] = [
  Student { name: "Alice", grade: 95 },
  Student { name: "Bob", grade: 82 },
  Student { name: "Charlie", grade: 88 }
]

mut sum = 0
for student in students {
  io.print("{{student.name}} got a {{student.grade.to_str()}}")
  sum = sum + student.grade
}

let average = sum / students.size
io.print("Class average is {{average.to_str()}}")
