use go:fmt

fn main() {
  mut numbers: [Int] = []
  fmt::Println("numbers.size = {numbers.size()}")

  fmt::Println("adding numbers from 0 to 10")
  for i in 0..10 {
    numbers.push(i)
  }

  fmt::Println("numbers.size = {numbers.size()}")
  for n in numbers {
    fmt::Println(n)
  }

  match numbers.at(6) {
    value => fmt::Println("7th element = {value}"),
    _ => fmt::Println("7th element missing"),
  }
}
