use go:fmt

struct Student {
  name: Str,
  grade: Int,
}

fn main() {
  let students: [Student] = [
    Student{name: "Alice", grade: 95},
    Student{name: "Bob", grade: 82},
    Student{name: "Charlie", grade: 88},
  ]

  mut sum = 0
  for student in students {
    fmt::Println("{student.name} got a {student.grade}")
    sum = sum + student.grade
  }

  let average = sum / students.size()
  fmt::Println("Class average is {average}")
}
