use ard/io

struct Student {
  name: Str,
  grade: Int
}

fn main() {
  let students: [Student] = [
    Student { name: "Alice", grade: 95 },
    Student { name: "Bob", grade: 82 },
    Student { name: "Charlie", grade: 88 }
  ]

  mut sum = 0
  for student in students {
    io::print("{student.name} got a {student.grade}")
    sum = sum + student.grade
  }

  let average = sum / students.size()
  io::print("Class average is {average}")
}
