use ard/http

fn main() {
  http::serve2(3000, [
    "/": fn(req: http::Request, mut res: http::Response) {
      res.body = "Hello, World!"
    },
    "/me": fn(req: http::Request, mut res: http::Response) {
      res.body = "this is {req.path().or("")}"
    },
    "/error": fn(req: http::Request, mut res: http::Response) {
      res.status = 400
      res.body = "Bad request"
    },
  ]).expect("Error serving at 3000")
}
