use ard/http

fn main() {
  let routes: [Str:http::HandlerFn] = [
    "/": fn(req: http::Request, mut res: http::Response) {
      res.body = "Hello, World!"
    },
    "/me": fn(req: http::Request, mut res: http::Response) {
      res.body = "this is {req.path().or("")}"
    },
    "/error": fn(req: http::Request, mut res: http::Response) {
      res.status = 400
      res.body = "Bad request"
    },
  ]

  http::serve(8000, routes).expect("Error serving at 3000")
}
