package javascript

import (
	"strconv"
	"strings"

	"github.com/akonwi/ard/pretty"
)

const jsLineWidth = 100
const jsIndentWidth = 2

type jsDoc = pretty.Doc

type jsIfClause struct {
	Condition string
	Body      string
}

type jsObjectField struct {
	Key   string
	Value string
}

func jsText(value string) jsDoc                  { return pretty.TextDoc(value) }
func jsConcat(parts ...jsDoc) jsDoc              { return pretty.ConcatDocs(parts...) }
func jsGroup(content jsDoc) jsDoc                { return pretty.GroupDoc(content) }
func jsIndent(content jsDoc) jsDoc               { return pretty.IndentDoc(content) }
func jsLine() jsDoc                              { return pretty.LineDoc() }
func jsSoftLine() jsDoc                          { return pretty.SoftLine() }
func jsHardLine() jsDoc                          { return pretty.HardLine() }
func jsJoin(separator jsDoc, docs []jsDoc) jsDoc { return pretty.Join(separator, docs) }

func renderJSDoc(document jsDoc) string {
	return pretty.Print(document, jsLineWidth, jsIndentWidth)
}

func jsImportDoc(value string) jsDoc {
	return jsText(value)
}

func jsModulePreambleDoc(imports []string, target string) jsDoc {
	parts := make([]jsDoc, 0, len(imports)+4)
	for _, item := range imports {
		parts = append(parts, jsImportDoc(item), jsHardLine())
	}
	if len(imports) > 0 {
		parts = append(parts, jsHardLine())
	}
	parts = append(parts,
		jsText("// Generated by Ard JavaScript backend (early preview)."),
		jsHardLine(),
		jsText("// Target: "+target),
		jsHardLine(),
	)
	return jsConcat(parts...)
}

func jsExportListDoc(names []string) jsDoc {
	if len(names) == 0 {
		return jsText("")
	}
	items := make([]jsDoc, 0, len(names))
	for _, name := range names {
		items = append(items, jsText(name))
	}
	body := jsJoin(jsConcat(jsText(","), jsLine()), items)
	return jsGroup(jsConcat(
		jsText("export {"),
		jsIndent(jsConcat(jsLine(), body)),
		jsLine(),
		jsText("};"),
	))
}

func jsNamespaceImportLine(alias string, importPath string) string {
	return "import * as " + alias + " from " + strconv.Quote(importPath) + ";"
}

func jsNamedImportLine(names []string, importPath string) string {
	return "import { " + strings.Join(names, ", ") + " } from " + strconv.Quote(importPath) + ";"
}

func jsBlockDoc(header string, body string) jsDoc {
	trimmed := strings.TrimSpace(body)
	if trimmed == "" {
		return jsText(header + " {}")
	}
	return jsGroup(jsConcat(
		jsText(header+" {"),
		jsIndent(jsConcat(jsHardLine(), jsText(trimmed))),
		jsHardLine(),
		jsText("}"),
	))
}

func jsBareBlockDoc(body string) jsDoc {
	trimmed := strings.TrimSpace(body)
	if trimmed == "" {
		return jsText("{}")
	}
	return jsGroup(jsConcat(
		jsText("{"),
		jsIndent(jsConcat(jsHardLine(), jsText(trimmed))),
		jsHardLine(),
		jsText("}"),
	))
}

func jsIfDoc(condition string, thenBody string, elseDoc jsDoc) jsDoc {
	base := jsBlockDoc("if ("+condition+")", thenBody)
	if elseDoc == nil {
		return base
	}
	return jsConcat(base, jsText(" else "), elseDoc)
}

func jsTryCatchDoc(catchVar string, tryBody string, catchBody string) jsDoc {
	return jsConcat(
		jsBlockDoc("try", tryBody),
		jsText(" catch ("+catchVar+") "),
		jsBareBlockDoc(catchBody),
	)
}

func jsIIFEDoc(body string) jsDoc {
	return jsConcat(
		jsText("(() => "),
		jsBareBlockDoc(body),
		jsText(")()"),
	)
}

func jsCallDoc(callee string, args []string) jsDoc {
	if len(args) == 0 {
		return jsText(callee + "()")
	}
	items := make([]jsDoc, 0, len(args))
	for _, arg := range args {
		items = append(items, jsText(arg))
	}
	body := jsJoin(jsConcat(jsText(","), jsLine()), items)
	return jsGroup(jsConcat(
		jsText(callee+"("),
		jsIndent(jsConcat(jsSoftLine(), body)),
		jsSoftLine(),
		jsText(")"),
	))
}

func jsArrayDoc(items []string) jsDoc {
	if len(items) == 0 {
		return jsText("[]")
	}
	docs := make([]jsDoc, 0, len(items))
	for _, item := range items {
		docs = append(docs, jsText(item))
	}
	body := jsJoin(jsConcat(jsText(","), jsLine()), docs)
	return jsGroup(jsConcat(
		jsText("["),
		jsIndent(jsConcat(jsSoftLine(), body)),
		jsSoftLine(),
		jsText("]"),
	))
}

func jsObjectDoc(fields []jsObjectField) jsDoc {
	if len(fields) == 0 {
		return jsText("{}")
	}
	docs := make([]jsDoc, 0, len(fields))
	for _, field := range fields {
		docs = append(docs, jsConcat(jsText(field.Key+": "), jsText(field.Value)))
	}
	body := jsJoin(jsConcat(jsText(","), jsLine()), docs)
	return jsGroup(jsConcat(
		jsText("{"),
		jsIndent(jsConcat(jsSoftLine(), body)),
		jsSoftLine(),
		jsText("}"),
	))
}

func jsExprStmtDoc(expr string) jsDoc {
	return jsConcat(jsText(expr), jsText(";"))
}

func jsAssignDoc(left string, right string) jsDoc {
	return jsConcat(jsText(left+" = "), jsText(right), jsText(";"))
}

func jsVarDeclDoc(keyword string, name string, value string) jsDoc {
	return jsConcat(jsText(keyword+" "+name+" = "), jsText(value), jsText(";"))
}

func jsReturnDoc(value string) jsDoc {
	return jsConcat(jsText("return "), jsText(value), jsText(";"))
}

func jsThrowDoc(value string) jsDoc {
	return jsConcat(jsText("throw "), jsText(value), jsText(";"))
}

func jsIfChainDoc(clauses []jsIfClause, elseDoc jsDoc) jsDoc {
	if len(clauses) == 0 {
		if elseDoc == nil {
			return jsText("")
		}
		return elseDoc
	}
	return jsIfDoc(clauses[0].Condition, clauses[0].Body, jsIfChainDoc(clauses[1:], elseDoc))
}

func jsClassDoc(name string, members []string) jsDoc {
	body := strings.Join(members, "\n\n")
	return jsBlockDoc("class "+name, body)
}
