package javascript

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/akonwi/ard/backend"
	"github.com/akonwi/ard/checker"
	"github.com/akonwi/ard/parse"
)

type emitOptions struct {
	invokeMain bool
}

type emitter struct {
	target            string
	builder           strings.Builder
	indentLevel       int
	moduleVars        map[string]string
	currentModule     string
	currentFunction   string
	currentReceiver   string
	currentReturnType checker.Type
}

func Build(inputPath, outputPath, target string) (string, error) {
	module, _, err := loadModule(inputPath, target)
	if err != nil {
		return "", err
	}

	source, err := emitSource(module, target, emitOptions{})
	if err != nil {
		return "", err
	}

	resolvedOutputPath, err := filepath.Abs(outputPath)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(resolvedOutputPath), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(resolvedOutputPath, source, 0o644); err != nil {
		return "", err
	}
	return outputPath, nil
}

func Run(inputPath, target string, _ []string) error {
	if target == backend.TargetJSBrowser {
		return fmt.Errorf("js-browser cannot be run directly; build and serve the emitted module instead")
	}
	if target != backend.TargetJSServer {
		return fmt.Errorf("unsupported JavaScript run target: %s", target)
	}
	if _, err := exec.LookPath("node"); err != nil {
		return fmt.Errorf("node is required to run js-server output: %w", err)
	}

	module, _, err := loadModule(inputPath, target)
	if err != nil {
		return err
	}

	source, err := emitSource(module, target, emitOptions{invokeMain: true})
	if err != nil {
		return err
	}

	tmpDir, err := os.MkdirTemp("", "ard-js-run-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	entryPath := filepath.Join(tmpDir, "main.mjs")
	if err := os.WriteFile(entryPath, source, 0o644); err != nil {
		return err
	}

	cmd := exec.Command("node", entryPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	cmd.Env = append([]string{}, os.Environ()...)
	return cmd.Run()
}

func loadModule(inputPath string, target string) (checker.Module, *checker.ProjectInfo, error) {
	sourceCode, err := os.ReadFile(inputPath)
	if err != nil {
		return nil, nil, fmt.Errorf("error reading file %s - %v", inputPath, err)
	}

	result := parse.Parse(sourceCode, inputPath)
	if len(result.Errors) > 0 {
		result.PrintErrors()
		return nil, nil, fmt.Errorf("parse errors")
	}
	program := result.Program

	workingDir := filepath.Dir(inputPath)
	moduleResolver, err := checker.NewModuleResolver(workingDir)
	if err != nil {
		return nil, nil, fmt.Errorf("error initializing module resolver: %w", err)
	}

	relPath, err := filepath.Rel(workingDir, inputPath)
	if err != nil {
		relPath = inputPath
	}

	c := checker.New(relPath, program, moduleResolver, checker.CheckOptions{Target: target})
	c.Check()
	if c.HasErrors() {
		for _, diagnostic := range c.Diagnostics() {
			fmt.Println(diagnostic)
		}
		return nil, nil, fmt.Errorf("type errors")
	}

	return c.Module(), moduleResolver.GetProjectInfo(), nil
}

func emitSource(root checker.Module, target string, options emitOptions) ([]byte, error) {
	modules, err := collectUserModules(root)
	if err != nil {
		return nil, err
	}

	e := &emitter{
		target:     target,
		moduleVars: make(map[string]string),
	}
	for _, module := range modules {
		e.moduleVars[module.Path()] = moduleVarName(module.Path())
	}

	e.line("// Generated by Ard JavaScript backend (early preview).")
	e.line("// Target: " + target)
	e.line("")
	e.line("function makeArdError(kind, moduleName, fnName, line, message, extra = {}) {")
	e.indent(func() {
		e.line("const error = new globalThis.Error(message);")
		e.line("error.ard_error = kind;")
		e.line("error.module = moduleName;")
		e.line("error.function = fnName;")
		e.line("error.line = line;")
		e.line("for (const key in extra) error[key] = extra[key];")
		e.line("return error;")
	})
	e.line("}")
	e.line("")
	e.line("function makeTryReturn(value) {")
	e.indent(func() {
		e.line("return { __ard_try_return: true, value };")
	})
	e.line("}")
	e.line("")
	e.line("class Maybe {")
	e.indent(func() {
		e.line("static some(value) {")
		e.indent(func() {
			e.line("const maybe = new Maybe();")
			e.line("maybe.value = value;")
			e.line("return maybe;")
		})
		e.line("}")
		e.line("")
		e.line("static none() {")
		e.indent(func() {
			e.line("return new Maybe();")
		})
		e.line("}")
		e.line("")
		e.line("isSome() {")
		e.indent(func() {
			e.line(`return Object.prototype.hasOwnProperty.call(this, "value");`)
		})
		e.line("}")
		e.line("")
		e.line("isNone() {")
		e.indent(func() {
			e.line("return !this.isSome();")
		})
		e.line("}")
		e.line("")
		e.line("or(fallback) {")
		e.indent(func() {
			e.line("return this.isSome() ? this.value : fallback;")
		})
		e.line("}")
		e.line("")
		e.line("expect(message) {")
		e.indent(func() {
			e.line("if (this.isSome()) return this.value;")
			e.line(`throw makeArdError("panic", "ard/maybe", "expect", 0, message);`)
		})
		e.line("}")
		e.line("")
		e.line("map(fn) {")
		e.indent(func() {
			e.line("return this.isSome() ? Maybe.some(fn(this.value)) : Maybe.none();")
		})
		e.line("}")
		e.line("")
		e.line("andThen(fn) {")
		e.indent(func() {
			e.line("return this.isSome() ? fn(this.value) : Maybe.none();")
		})
		e.line("}")
	})
	e.line("}")
	e.line("")
	e.line("class Result {")
	e.indent(func() {
		e.line("static ok(value) {")
		e.indent(func() {
			e.line("const result = new Result();")
			e.line("result.ok = value;")
			e.line("return result;")
		})
		e.line("}")
		e.line("")
		e.line("static err(error) {")
		e.indent(func() {
			e.line("const result = new Result();")
			e.line("result.error = error;")
			e.line("return result;")
		})
		e.line("}")
		e.line("")
		e.line("isOk() {")
		e.indent(func() {
			e.line(`return Object.prototype.hasOwnProperty.call(this, "ok");`)
		})
		e.line("}")
		e.line("")
		e.line("isErr() {")
		e.indent(func() {
			e.line(`return Object.prototype.hasOwnProperty.call(this, "error");`)
		})
		e.line("}")
		e.line("")
		e.line("or(fallback) {")
		e.indent(func() {
			e.line("return this.isOk() ? this.ok : fallback;")
		})
		e.line("}")
		e.line("")
		e.line("expect(message) {")
		e.indent(func() {
			e.line("if (this.isOk()) return this.ok;")
			e.line(`throw makeArdError("panic", "ard/result", "expect", 0, message);`)
		})
		e.line("}")
		e.line("")
		e.line("map(fn) {")
		e.indent(func() {
			e.line("return this.isOk() ? Result.ok(fn(this.ok)) : this;")
		})
		e.line("}")
		e.line("")
		e.line("mapErr(fn) {")
		e.indent(func() {
			e.line("return this.isErr() ? Result.err(fn(this.error)) : this;")
		})
		e.line("}")
		e.line("")
		e.line("andThen(fn) {")
		e.indent(func() {
			e.line("return this.isOk() ? fn(this.ok) : this;")
		})
		e.line("}")
	})
	e.line("}")
	e.line("")

	for _, module := range modules {
		if err := e.emitModuleWrapper(module); err != nil {
			return nil, err
		}
	}

	if err := e.emitRootModule(root); err != nil {
		return nil, err
	}

	if options.invokeMain {
		if !moduleHasPublicOrPrivateFunction(root.Program(), "main") {
			return nil, fmt.Errorf("js-server run requires fn main()")
		}
		e.line("")
		e.line("main();")
	}

	return []byte(e.builder.String()), nil
}

func collectUserModules(root checker.Module) ([]checker.Module, error) {
	seen := map[string]bool{}
	ordered := make([]checker.Module, 0)
	var visit func(module checker.Module) error
	visit = func(module checker.Module) error {
		if module == nil || module.Program() == nil {
			return nil
		}
		for _, imported := range module.Program().Imports {
			if imported == nil {
				continue
			}
			if strings.HasPrefix(imported.Path(), "ard/") {
				continue
			}
			if seen[imported.Path()] {
				continue
			}
			seen[imported.Path()] = true
			if err := visit(imported); err != nil {
				return err
			}
			ordered = append(ordered, imported)
		}
		return nil
	}
	if err := visit(root); err != nil {
		return nil, err
	}
	return ordered, nil
}

func moduleHasPublicOrPrivateFunction(program *checker.Program, name string) bool {
	for _, stmt := range program.Statements {
		fn, ok := stmt.Expr.(*checker.FunctionDef)
		if ok && fn.Name == name && fn.Receiver == "" {
			return true
		}
	}
	return false
}

func (e *emitter) emitModuleWrapper(module checker.Module) error {
	moduleName := e.moduleVars[module.Path()]
	e.line(fmt.Sprintf("const %s = (() => {", moduleName))
	e.indent(func() {
		err := e.emitModuleStatements(module)
		if err != nil {
			panic(err)
		}
		exports := exportedNames(module.Program())
		if len(exports) == 0 {
			e.line("return {};")
			return
		}
		parts := make([]string, 0, len(exports))
		for _, name := range exports {
			parts = append(parts, name+": "+jsName(name))
		}
		e.line("return { " + strings.Join(parts, ", ") + " };")
	})
	e.line("})();")
	e.line("")
	return nil
}

func (e *emitter) emitRootModule(module checker.Module) error {
	if err := e.emitModuleStatements(module); err != nil {
		return err
	}
	exports := exportedNames(module.Program())
	if len(exports) == 0 {
		return nil
	}
	e.line("")
	e.line("export { " + strings.Join(exports, ", ") + " };")
	return nil
}

func exportedNames(program *checker.Program) []string {
	names := make([]string, 0)
	seen := map[string]bool{}
	for _, stmt := range program.Statements {
		switch expr := stmt.Expr.(type) {
		case *checker.FunctionDef:
			if expr.Private || expr.Receiver != "" || seen[expr.Name] {
				continue
			}
			seen[expr.Name] = true
			names = append(names, expr.Name)
		case *checker.ExternalFunctionDef:
			if expr.Private || seen[expr.Name] {
				continue
			}
			seen[expr.Name] = true
			names = append(names, expr.Name)
		}
		switch def := stmt.Stmt.(type) {
		case *checker.VariableDef:
			if def.Mutable || seen[def.Name] {
				continue
			}
			seen[def.Name] = true
			names = append(names, def.Name)
		case *checker.StructDef:
			if def.Private || seen[def.Name] {
				continue
			}
			seen[def.Name] = true
			names = append(names, def.Name)
		}
	}
	sort.Strings(names)
	return names
}

func (e *emitter) emitModuleStatements(module checker.Module) error {
	prevModule := e.currentModule
	e.currentModule = module.Path()
	defer func() { e.currentModule = prevModule }()

	for _, stmt := range module.Program().Statements {
		if err := e.emitTopLevelStatement(stmt); err != nil {
			return err
		}
	}
	return nil
}

func (e *emitter) emitTopLevelStatement(stmt checker.Statement) error {
	if stmt.Break {
		return fmt.Errorf("break is not valid at the top level")
	}
	if stmt.Stmt != nil {
		return e.emitNonProducing(stmt.Stmt)
	}
	if stmt.Expr == nil {
		return nil
	}
	switch expr := stmt.Expr.(type) {
	case *checker.FunctionDef:
		return e.emitFunctionDef(expr)
	case *checker.ExternalFunctionDef:
		return e.emitExternalFunctionDef(expr)
	default:
		value, err := e.emitExpr(expr)
		if err != nil {
			return err
		}
		e.line(value + ";")
		return nil
	}
}

func (e *emitter) emitFunctionDef(fn *checker.FunctionDef) error {
	if fn.Receiver != "" {
		return nil
	}
	params := make([]string, 0, len(fn.Parameters))
	for _, param := range fn.Parameters {
		params = append(params, jsName(param.Name))
	}
	e.line(fmt.Sprintf("function %s(%s) {", jsName(fn.Name), strings.Join(params, ", ")))
	prevFunction := e.currentFunction
	prevReturnType := e.currentReturnType
	e.currentFunction = fn.Name
	e.currentReturnType = fn.ReturnType
	e.indent(func() {
		err := e.emitFunctionBoundary(fn.Body)
		if err != nil {
			panic(err)
		}
	})
	e.currentFunction = prevFunction
	e.currentReturnType = prevReturnType
	e.line("}")
	e.line("")
	return nil
}

func (e *emitter) emitExternalFunctionDef(fn *checker.ExternalFunctionDef) error {
	params := make([]string, 0, len(fn.Parameters))
	for _, param := range fn.Parameters {
		params = append(params, jsName(param.Name))
	}
	e.line(fmt.Sprintf("function %s(%s) {", jsName(fn.Name), strings.Join(params, ", ")))
	e.indent(func() {
		message := strconv.Quote("external function not implemented for JavaScript backend: " + fn.ExternalBinding)
		e.line("throw makeArdError(\"extern\", " + strconv.Quote(e.currentModule) + ", " + strconv.Quote(fn.Name) + ", 0, " + message + ");")
	})
	e.line("}")
	e.line("")
	return nil
}

func (e *emitter) emitFunctionBoundary(body *checker.Block) error {
	e.line("try {")
	e.indent(func() {
		err := e.emitBlock(body, true)
		if err != nil {
			panic(err)
		}
	})
	e.line("} catch (__ard_try) {")
	e.indent(func() {
		e.line("if (__ard_try && __ard_try.__ard_try_return) return __ard_try.value;")
		e.line("throw __ard_try;")
	})
	e.line("}")
	return nil
}

func (e *emitter) emitBlock(block *checker.Block, returns bool) error {
	if block == nil {
		if returns {
			e.line("return undefined;")
		}
		return nil
	}
	lastExpr := -1
	for i := len(block.Stmts) - 1; i >= 0; i-- {
		if block.Stmts[i].Expr != nil {
			lastExpr = i
			break
		}
	}
	for i, stmt := range block.Stmts {
		if stmt.Break {
			e.line("break;")
			continue
		}
		if stmt.Stmt != nil {
			if err := e.emitNonProducing(stmt.Stmt); err != nil {
				return err
			}
			continue
		}
		if stmt.Expr == nil {
			continue
		}
		if returns && i == lastExpr {
			if err := e.emitTailExpr(stmt.Expr); err != nil {
				return err
			}
			continue
		}
		value, err := e.emitExpr(stmt.Expr)
		if err != nil {
			return err
		}
		e.line(value + ";")
	}
	if returns && lastExpr == -1 {
		e.line("return undefined;")
	}
	return nil
}

func (e *emitter) emitTailExpr(expr checker.Expression) error {
	switch expr := expr.(type) {
	case *checker.If:
		return e.emitIf(expr, true)
	case *checker.Block:
		return e.emitBlock(expr, true)
	case *checker.Panic:
		message, err := e.emitExpr(expr.Message)
		if err != nil {
			return err
		}
		e.line("throw makeArdError(\"panic\", " + strconv.Quote(e.currentModule) + ", " + strconv.Quote(e.currentFunction) + ", 0, " + message + ");")
		return nil
	case *checker.TryOp:
		value, err := e.emitExpr(expr)
		if err != nil {
			return err
		}
		e.line("return " + value + ";")
		return nil
	default:
		value, err := e.emitExpr(expr)
		if err != nil {
			return err
		}
		e.line("return " + value + ";")
		return nil
	}
}

func (e *emitter) emitTryCatchBlockValue(block *checker.Block, catchVar string, catchValue string) (string, error) {
	child := &emitter{
		target:            e.target,
		moduleVars:        e.moduleVars,
		currentModule:     e.currentModule,
		currentFunction:   e.currentFunction,
		currentReceiver:   e.currentReceiver,
		currentReturnType: e.currentReturnType,
	}
	child.line("(() => {")
	child.indent(func() {
		if catchVar != "" && catchVar != "_" {
			child.line("const " + jsName(catchVar) + " = " + catchValue + ";")
		}
		err := child.emitBlock(block, true)
		if err != nil {
			panic(err)
		}
	})
	child.line("})()")
	return strings.TrimSpace(child.builder.String()), nil
}

func (e *emitter) emitTryExpr(op *checker.TryOp) (string, error) {
	subject, err := e.emitExpr(op.Expr())
	if err != nil {
		return "", err
	}
	child := &emitter{
		target:            e.target,
		moduleVars:        e.moduleVars,
		currentModule:     e.currentModule,
		currentFunction:   e.currentFunction,
		currentReceiver:   e.currentReceiver,
		currentReturnType: e.currentReturnType,
	}
	child.line("(() => {")
	child.indent(func() {
		child.line("const __try = " + subject + ";")
		switch op.Kind {
		case checker.TryResult:
			if op.CatchBlock != nil {
				catchExpr, err := e.emitTryCatchBlockValue(op.CatchBlock, op.CatchVar, "__try.error")
				if err != nil {
					panic(err)
				}
				child.line("if (__try.isErr()) throw makeTryReturn(" + catchExpr + ");")
			} else {
				child.line("if (__try.isErr()) throw makeTryReturn(Result.err(__try.error));")
			}
			child.line("return __try.ok;")
		case checker.TryMaybe:
			if op.CatchBlock != nil {
				catchExpr, err := e.emitTryCatchBlockValue(op.CatchBlock, op.CatchVar, "undefined")
				if err != nil {
					panic(err)
				}
				child.line("if (__try.isNone()) throw makeTryReturn(" + catchExpr + ");")
			} else {
				child.line("if (__try.isNone()) throw makeTryReturn(Maybe.none());")
			}
			child.line("return __try.value;")
		default:
			panic(fmt.Errorf("unsupported try kind: %v", op.Kind))
		}
	})
	child.line("})()")
	return strings.TrimSpace(child.builder.String()), nil
}

func (e *emitter) emitIf(expr *checker.If, returns bool) error {
	condition, err := e.emitExpr(expr.Condition)
	if err != nil {
		return err
	}
	e.line("if (" + condition + ") {")
	e.indent(func() {
		err = e.emitBlock(expr.Body, returns)
		if err != nil {
			panic(err)
		}
	})
	e.line("}")
	if expr.ElseIf != nil {
		e.line("else {")
		e.indent(func() {
			err = e.emitIf(expr.ElseIf, returns)
			if err != nil {
				panic(err)
			}
		})
		e.line("}")
		return nil
	}
	if expr.Else != nil {
		e.line("else {")
		e.indent(func() {
			err = e.emitBlock(expr.Else, returns)
			if err != nil {
				panic(err)
			}
		})
		e.line("}")
		return nil
	}
	if returns {
		e.line("return undefined;")
	}
	return nil
}

func (e *emitter) emitNonProducing(stmt checker.NonProducing) error {
	switch stmt := stmt.(type) {
	case *checker.StructDef:
		return e.emitStructDef(stmt)
	case *checker.VariableDef:
		value, err := e.emitExpr(stmt.Value)
		if err != nil {
			return err
		}
		keyword := "const"
		if stmt.Mutable {
			keyword = "let"
		}
		e.line(fmt.Sprintf("%s %s = %s;", keyword, jsName(stmt.Name), value))
		return nil
	case *checker.Reassignment:
		target, err := e.emitAssignable(stmt.Target)
		if err != nil {
			return err
		}
		value, err := e.emitExpr(stmt.Value)
		if err != nil {
			return err
		}
		e.line(target + " = " + value + ";")
		return nil
	case checker.WhileLoop:
		condition, err := e.emitExpr(stmt.Condition)
		if err != nil {
			return err
		}
		e.line("while (" + condition + ") {")
		e.indent(func() {
			err = e.emitBlock(stmt.Body, false)
			if err != nil {
				panic(err)
			}
		})
		e.line("}")
		return nil
	case checker.ForLoop:
		init, err := e.emitForInit(stmt.Init)
		if err != nil {
			return err
		}
		condition, err := e.emitExpr(stmt.Condition)
		if err != nil {
			return err
		}
		update, err := e.emitReassignmentInline(stmt.Update)
		if err != nil {
			return err
		}
		e.line("for (" + init + "; " + condition + "; " + update + ") {")
		e.indent(func() {
			err = e.emitBlock(stmt.Body, false)
			if err != nil {
				panic(err)
			}
		})
		e.line("}")
		return nil
	default:
		return fmt.Errorf("js backend does not yet support statement type %T", stmt)
	}
}

func (e *emitter) emitForInit(def *checker.VariableDef) (string, error) {
	if def == nil {
		return "", nil
	}
	value, err := e.emitExpr(def.Value)
	if err != nil {
		return "", err
	}
	keyword := "const"
	if def.Mutable {
		keyword = "let"
	}
	return fmt.Sprintf("%s %s = %s", keyword, jsName(def.Name), value), nil
}

func (e *emitter) emitReassignmentInline(stmt *checker.Reassignment) (string, error) {
	target, err := e.emitAssignable(stmt.Target)
	if err != nil {
		return "", err
	}
	value, err := e.emitExpr(stmt.Value)
	if err != nil {
		return "", err
	}
	return target + " = " + value, nil
}

func (e *emitter) emitAssignable(expr checker.Expression) (string, error) {
	switch expr := expr.(type) {
	case *checker.Variable:
		return e.emitVariableName(expr.Name()), nil
	case *checker.InstanceProperty:
		subject, err := e.emitExpr(expr.Subject)
		if err != nil {
			return "", err
		}
		return subject + "." + jsName(expr.Property), nil
	default:
		return "", fmt.Errorf("js backend does not yet support assignment target %T", expr)
	}
}

func (e *emitter) emitExpr(expr checker.Expression) (string, error) {
	switch expr := expr.(type) {
	case *checker.StructInstance:
		return e.emitStructInstance(expr, jsName(expr.Name))
	case *checker.ModuleStructInstance:
		moduleVar, ok := e.moduleVars[expr.Module]
		if !ok {
			return "", fmt.Errorf("unknown imported module %s", expr.Module)
		}
		return e.emitStructInstance(expr.Property, moduleVar+"."+jsName(expr.Property.Name))
	case *checker.InstanceProperty:
		subject, err := e.emitExpr(expr.Subject)
		if err != nil {
			return "", err
		}
		return subject + "." + jsName(expr.Property), nil
	case *checker.ListLiteral:
		elements, err := e.emitArgs(expr.Elements)
		if err != nil {
			return "", err
		}
		return "[" + strings.Join(elements, ", ") + "]", nil
	case *checker.StrLiteral:
		return strconv.Quote(expr.Value), nil
	case *checker.TemplateStr:
		return e.emitTemplateStr(expr)
	case *checker.BoolLiteral:
		if expr.Value {
			return "true", nil
		}
		return "false", nil
	case *checker.VoidLiteral:
		return "undefined", nil
	case *checker.IntLiteral:
		return strconv.Itoa(expr.Value), nil
	case *checker.FloatLiteral:
		return strconv.FormatFloat(expr.Value, 'g', -1, 64), nil
	case *checker.Variable:
		return e.emitVariableName(expr.Name()), nil
	case *checker.ModuleSymbol:
		moduleVar, ok := e.moduleVars[expr.Module]
		if !ok {
			return "", fmt.Errorf("unknown imported module %s", expr.Module)
		}
		return moduleVar + "." + jsName(expr.Symbol.Name), nil
	case *checker.FunctionDef:
		return e.emitFunctionLiteral(expr)
	case *checker.FunctionCall:
		args, err := e.emitArgs(expr.Args)
		if err != nil {
			return "", err
		}
		return jsName(expr.Name) + "(" + strings.Join(args, ", ") + ")", nil
	case *checker.ModuleFunctionCall:
		if expr.Module == "ard/maybe" {
			return e.emitMaybeModuleCall(expr)
		}
		if expr.Module == "ard/result" {
			return e.emitResultModuleCall(expr)
		}
		moduleVar, ok := e.moduleVars[expr.Module]
		if !ok {
			return "", fmt.Errorf("unknown imported module %s", expr.Module)
		}
		args, err := e.emitArgs(expr.Call.Args)
		if err != nil {
			return "", err
		}
		return moduleVar + "." + jsName(expr.Call.Name) + "(" + strings.Join(args, ", ") + ")", nil
	case *checker.InstanceMethod:
		subject, err := e.emitExpr(expr.Subject)
		if err != nil {
			return "", err
		}
		args, err := e.emitArgs(expr.Method.Args)
		if err != nil {
			return "", err
		}
		return subject + "." + jsName(expr.Method.Name) + "(" + strings.Join(args, ", ") + ")", nil
	case *checker.CopyExpression:
		return e.emitExpr(expr.Expr)
	case *checker.TryOp:
		return e.emitTryExpr(expr)
	case *checker.StrMethod:
		return e.emitStrMethod(expr)
	case *checker.IntMethod:
		return e.emitIntMethod(expr)
	case *checker.FloatMethod:
		return e.emitFloatMethod(expr)
	case *checker.BoolMethod:
		return e.emitBoolMethod(expr)
	case *checker.BoolMatch:
		return e.emitBoolMatch(expr)
	case *checker.OptionMatch:
		return e.emitOptionMatch(expr)
	case *checker.ResultMatch:
		return e.emitResultMatch(expr)
	case *checker.ListMethod:
		return e.emitListMethod(expr)
	case *checker.MaybeMethod:
		return e.emitMaybeMethod(expr)
	case *checker.ResultMethod:
		return e.emitResultMethod(expr)
	case *checker.IntAddition:
		return e.emitBinary(expr.Left, "+", expr.Right)
	case *checker.IntSubtraction:
		return e.emitBinary(expr.Left, "-", expr.Right)
	case *checker.IntMultiplication:
		return e.emitBinary(expr.Left, "*", expr.Right)
	case *checker.IntDivision:
		return e.emitBinary(expr.Left, "/", expr.Right)
	case *checker.IntModulo:
		return e.emitBinary(expr.Left, "%", expr.Right)
	case *checker.IntGreater:
		return e.emitBinary(expr.Left, ">", expr.Right)
	case *checker.IntGreaterEqual:
		return e.emitBinary(expr.Left, ">=", expr.Right)
	case *checker.IntLess:
		return e.emitBinary(expr.Left, "<", expr.Right)
	case *checker.IntLessEqual:
		return e.emitBinary(expr.Left, "<=", expr.Right)
	case *checker.FloatAddition:
		return e.emitBinary(expr.Left, "+", expr.Right)
	case *checker.FloatSubtraction:
		return e.emitBinary(expr.Left, "-", expr.Right)
	case *checker.FloatMultiplication:
		return e.emitBinary(expr.Left, "*", expr.Right)
	case *checker.FloatDivision:
		return e.emitBinary(expr.Left, "/", expr.Right)
	case *checker.FloatGreater:
		return e.emitBinary(expr.Left, ">", expr.Right)
	case *checker.FloatGreaterEqual:
		return e.emitBinary(expr.Left, ">=", expr.Right)
	case *checker.FloatLess:
		return e.emitBinary(expr.Left, "<", expr.Right)
	case *checker.FloatLessEqual:
		return e.emitBinary(expr.Left, "<=", expr.Right)
	case *checker.StrAddition:
		return e.emitBinary(expr.Left, "+", expr.Right)
	case *checker.Equality:
		return e.emitBinary(expr.Left, "===", expr.Right)
	case *checker.And:
		return e.emitBinary(expr.Left, "&&", expr.Right)
	case *checker.Or:
		return e.emitBinary(expr.Left, "||", expr.Right)
	case *checker.Negation:
		value, err := e.emitExpr(expr.Value)
		if err != nil {
			return "", err
		}
		return "(-" + value + ")", nil
	case *checker.Not:
		value, err := e.emitExpr(expr.Value)
		if err != nil {
			return "", err
		}
		return "(!" + value + ")", nil
	case *checker.If:
		return e.emitInlineClosure(expr)
	case *checker.Block:
		return e.emitInlineClosure(expr)
	case *checker.Panic:
		message, err := e.emitExpr(expr.Message)
		if err != nil {
			return "", err
		}
		return "(() => { throw makeArdError(\"panic\", " + strconv.Quote(e.currentModule) + ", " + strconv.Quote(e.currentFunction) + ", 0, " + message + "); })()", nil
	default:
		return "", fmt.Errorf("js backend does not yet support expression type %T", expr)
	}
}

func (e *emitter) emitStructDef(def *checker.StructDef) error {
	fieldNames := sortedFieldNames(def.Fields)
	params := make([]string, 0, len(fieldNames))
	for _, field := range fieldNames {
		params = append(params, jsName(field))
	}

	e.line(fmt.Sprintf("class %s {", jsName(def.Name)))
	e.indent(func() {
		e.line("constructor(" + strings.Join(params, ", ") + ") {")
		e.indent(func() {
			for _, field := range fieldNames {
				name := jsName(field)
				e.line("this." + name + " = " + name + ";")
			}
		})
		e.line("}")
		methodNames := sortedFunctionNames(def.Methods)
		for _, methodName := range methodNames {
			e.line("")
			err := e.emitStructMethod(def, def.Methods[methodName])
			if err != nil {
				panic(err)
			}
		}
	})
	e.line("}")
	e.line("")
	return nil
}

func (e *emitter) emitStructMethod(def *checker.StructDef, method *checker.FunctionDef) error {
	params := make([]string, 0, len(method.Parameters))
	for _, param := range method.Parameters {
		params = append(params, jsName(param.Name))
	}

	e.line(fmt.Sprintf("%s(%s) {", jsName(method.Name), strings.Join(params, ", ")))
	prevFunction := e.currentFunction
	prevReceiver := e.currentReceiver
	prevReturnType := e.currentReturnType
	e.currentFunction = def.Name + "." + method.Name
	e.currentReceiver = method.Receiver
	e.currentReturnType = method.ReturnType
	e.indent(func() {
		err := e.emitFunctionBoundary(method.Body)
		if err != nil {
			panic(err)
		}
	})
	e.currentFunction = prevFunction
	e.currentReceiver = prevReceiver
	e.currentReturnType = prevReturnType
	e.line("}")
	return nil
}

func (e *emitter) emitStructInstance(instance *checker.StructInstance, ctor string) (string, error) {
	fieldNames := sortedStructInstanceFields(instance)
	args := make([]string, 0, len(fieldNames))
	for _, field := range fieldNames {
		value, err := e.emitExpr(instance.Fields[field])
		if err != nil {
			return "", err
		}
		args = append(args, value)
	}
	return "new " + ctor + "(" + strings.Join(args, ", ") + ")", nil
}

func (e *emitter) emitFunctionLiteral(def *checker.FunctionDef) (string, error) {
	child := &emitter{
		target:            e.target,
		moduleVars:        e.moduleVars,
		currentModule:     e.currentModule,
		currentFunction:   e.currentFunction,
		currentReceiver:   e.currentReceiver,
		currentReturnType: def.ReturnType,
	}
	params := make([]string, 0, len(def.Parameters))
	for _, param := range def.Parameters {
		params = append(params, jsName(param.Name))
	}
	child.line("function(" + strings.Join(params, ", ") + ") {")
	child.indent(func() {
		if err := child.emitFunctionBoundary(def.Body); err != nil {
			panic(err)
		}
	})
	child.line("}")
	return strings.TrimSpace(child.builder.String()), nil
}

func (e *emitter) emitListMethod(method *checker.ListMethod) (string, error) {
	subject, err := e.emitExpr(method.Subject)
	if err != nil {
		return "", err
	}
	args, err := e.emitArgs(method.Args)
	if err != nil {
		return "", err
	}

	switch method.Kind {
	case checker.ListSize:
		return subject + ".length", nil
	case checker.ListAt:
		if len(args) != 1 {
			return "", fmt.Errorf("list.at expects one arg")
		}
		return subject + "[" + args[0] + "]", nil
	case checker.ListPush:
		if len(args) != 1 {
			return "", fmt.Errorf("list.push expects one arg")
		}
		return e.emitMutationExpr(subject, []string{"__value.push(" + args[0] + ");"}, "__value")
	case checker.ListPrepend:
		if len(args) != 1 {
			return "", fmt.Errorf("list.prepend expects one arg")
		}
		return e.emitMutationExpr(subject, []string{"__value.unshift(" + args[0] + ");"}, "__value")
	case checker.ListSet:
		if len(args) != 2 {
			return "", fmt.Errorf("list.set expects two args")
		}
		return e.emitMutationExpr(subject, []string{"__value[" + args[0] + "] = " + args[1] + ";"}, "true")
	case checker.ListSwap:
		if len(args) != 2 {
			return "", fmt.Errorf("list.swap expects two args")
		}
		lines := []string{
			"const __tmp = __value[" + args[0] + "];",
			"__value[" + args[0] + "] = __value[" + args[1] + "];",
			"__value[" + args[1] + "] = __tmp;",
		}
		return e.emitMutationExpr(subject, lines, "undefined")
	case checker.ListSort:
		if len(args) != 1 {
			return "", fmt.Errorf("list.sort expects one arg")
		}
		cmp := args[0]
		lines := []string{
			"__value.sort((a, b) => " + cmp + "(a, b) ? -1 : (" + cmp + "(b, a) ? 1 : 0));",
		}
		return e.emitMutationExpr(subject, lines, "undefined")
	default:
		return "", fmt.Errorf("unsupported list method: %v", method.Kind)
	}
}

func (e *emitter) emitStrMethod(method *checker.StrMethod) (string, error) {
	subject, err := e.emitExpr(method.Subject)
	if err != nil {
		return "", err
	}
	args, err := e.emitArgs(method.Args)
	if err != nil {
		return "", err
	}
	switch method.Kind {
	case checker.StrSize:
		return subject + ".length", nil
	case checker.StrIsEmpty:
		return "(" + subject + ".length === 0)", nil
	case checker.StrContains:
		if len(args) != 1 {
			return "", fmt.Errorf("str.contains expects one arg")
		}
		return subject + ".includes(" + args[0] + ")", nil
	case checker.StrReplace:
		if len(args) != 2 {
			return "", fmt.Errorf("str.replace expects two args")
		}
		return subject + ".replace(" + args[0] + ", " + args[1] + ")", nil
	case checker.StrReplaceAll:
		if len(args) != 2 {
			return "", fmt.Errorf("str.replace_all expects two args")
		}
		return subject + ".replaceAll(" + args[0] + ", " + args[1] + ")", nil
	case checker.StrSplit:
		if len(args) != 1 {
			return "", fmt.Errorf("str.split expects one arg")
		}
		return subject + ".split(" + args[0] + ")", nil
	case checker.StrStartsWith:
		if len(args) != 1 {
			return "", fmt.Errorf("str.starts_with expects one arg")
		}
		return subject + ".startsWith(" + args[0] + ")", nil
	case checker.StrToStr:
		return subject, nil
	case checker.StrTrim:
		return subject + ".trim()", nil
	default:
		return "", fmt.Errorf("unsupported str method: %v", method.Kind)
	}
}

func (e *emitter) emitIntMethod(method *checker.IntMethod) (string, error) {
	subject, err := e.emitExpr(method.Subject)
	if err != nil {
		return "", err
	}
	switch method.Kind {
	case checker.IntToStr:
		return "String(" + subject + ")", nil
	default:
		return "", fmt.Errorf("unsupported int method: %v", method.Kind)
	}
}

func (e *emitter) emitFloatMethod(method *checker.FloatMethod) (string, error) {
	subject, err := e.emitExpr(method.Subject)
	if err != nil {
		return "", err
	}
	switch method.Kind {
	case checker.FloatToStr:
		return "String(" + subject + ")", nil
	case checker.FloatToInt:
		return "Math.trunc(" + subject + ")", nil
	default:
		return "", fmt.Errorf("unsupported float method: %v", method.Kind)
	}
}

func (e *emitter) emitBoolMethod(method *checker.BoolMethod) (string, error) {
	subject, err := e.emitExpr(method.Subject)
	if err != nil {
		return "", err
	}
	switch method.Kind {
	case checker.BoolToStr:
		return "String(" + subject + ")", nil
	default:
		return "", fmt.Errorf("unsupported bool method: %v", method.Kind)
	}
}

func (e *emitter) emitBoundBlockExpr(block *checker.Block, bindings []string) (string, error) {
	child := &emitter{
		target:            e.target,
		moduleVars:        e.moduleVars,
		currentModule:     e.currentModule,
		currentFunction:   e.currentFunction,
		currentReceiver:   e.currentReceiver,
		currentReturnType: e.currentReturnType,
	}
	child.line("(() => {")
	child.indent(func() {
		for _, binding := range bindings {
			child.line(binding)
		}
		err := child.emitBlock(block, true)
		if err != nil {
			panic(err)
		}
	})
	child.line("})()")
	return strings.TrimSpace(child.builder.String()), nil
}

func (e *emitter) emitBoolMatch(match *checker.BoolMatch) (string, error) {
	subject, err := e.emitExpr(match.Subject)
	if err != nil {
		return "", err
	}
	trueExpr, err := e.emitBoundBlockExpr(match.True, nil)
	if err != nil {
		return "", err
	}
	falseExpr, err := e.emitBoundBlockExpr(match.False, nil)
	if err != nil {
		return "", err
	}
	return "(() => { const __match = " + subject + "; return __match ? " + trueExpr + " : " + falseExpr + "; })()", nil
}

func (e *emitter) emitOptionMatch(match *checker.OptionMatch) (string, error) {
	subject, err := e.emitExpr(match.Subject)
	if err != nil {
		return "", err
	}
	someBindings := []string{}
	if match.Some != nil && match.Some.Pattern != nil {
		someBindings = append(someBindings, "const "+jsName(match.Some.Pattern.Name)+" = __match.value;")
	}
	someExpr, err := e.emitBoundBlockExpr(match.Some.Body, someBindings)
	if err != nil {
		return "", err
	}
	noneExpr, err := e.emitBoundBlockExpr(match.None, nil)
	if err != nil {
		return "", err
	}
	return "(() => { const __match = " + subject + "; return __match.isSome() ? " + someExpr + " : " + noneExpr + "; })()", nil
}

func (e *emitter) emitResultMatch(match *checker.ResultMatch) (string, error) {
	subject, err := e.emitExpr(match.Subject)
	if err != nil {
		return "", err
	}
	okBindings := []string{}
	if match.Ok != nil && match.Ok.Pattern != nil {
		okBindings = append(okBindings, "const "+jsName(match.Ok.Pattern.Name)+" = __match.ok;")
	}
	okExpr, err := e.emitBoundBlockExpr(match.Ok.Body, okBindings)
	if err != nil {
		return "", err
	}
	errBindings := []string{}
	if match.Err != nil && match.Err.Pattern != nil {
		errBindings = append(errBindings, "const "+jsName(match.Err.Pattern.Name)+" = __match.error;")
	}
	errExpr, err := e.emitBoundBlockExpr(match.Err.Body, errBindings)
	if err != nil {
		return "", err
	}
	return "(() => { const __match = " + subject + "; return __match.isOk() ? " + okExpr + " : " + errExpr + "; })()", nil
}

func (e *emitter) emitMaybeModuleCall(call *checker.ModuleFunctionCall) (string, error) {
	switch call.Call.Name {
	case "some":
		if len(call.Call.Args) != 1 {
			return "", fmt.Errorf("maybe::some expects one arg")
		}
		args, err := e.emitArgs(call.Call.Args)
		if err != nil {
			return "", err
		}
		return "Maybe.some(" + args[0] + ")", nil
	case "none":
		return "Maybe.none()", nil
	default:
		return "", fmt.Errorf("unsupported maybe module call: %s", call.Call.Name)
	}
}

func (e *emitter) emitResultModuleCall(call *checker.ModuleFunctionCall) (string, error) {
	switch call.Call.Name {
	case "ok":
		if len(call.Call.Args) != 1 {
			return "", fmt.Errorf("Result::ok expects one arg")
		}
		args, err := e.emitArgs(call.Call.Args)
		if err != nil {
			return "", err
		}
		return "Result.ok(" + args[0] + ")", nil
	case "err":
		if len(call.Call.Args) != 1 {
			return "", fmt.Errorf("Result::err expects one arg")
		}
		args, err := e.emitArgs(call.Call.Args)
		if err != nil {
			return "", err
		}
		return "Result.err(" + args[0] + ")", nil
	default:
		return "", fmt.Errorf("unsupported Result module call: %s", call.Call.Name)
	}
}

func (e *emitter) emitMaybeMethod(method *checker.MaybeMethod) (string, error) {
	subject, err := e.emitExpr(method.Subject)
	if err != nil {
		return "", err
	}
	args, err := e.emitArgs(method.Args)
	if err != nil {
		return "", err
	}
	failArgs := func(name string, want int) error {
		return fmt.Errorf("maybe.%s expects %d arg(s)", name, want)
	}

	switch method.Kind {
	case checker.MaybeExpect:
		if len(args) != 1 {
			return "", failArgs("expect", 1)
		}
		return subject + ".expect(" + args[0] + ")", nil
	case checker.MaybeIsNone:
		return subject + ".isNone()", nil
	case checker.MaybeIsSome:
		return subject + ".isSome()", nil
	case checker.MaybeOr:
		if len(args) != 1 {
			return "", failArgs("or", 1)
		}
		return subject + ".or(" + args[0] + ")", nil
	case checker.MaybeMap:
		if len(args) != 1 {
			return "", failArgs("map", 1)
		}
		return subject + ".map(" + args[0] + ")", nil
	case checker.MaybeAndThen:
		if len(args) != 1 {
			return "", failArgs("and_then", 1)
		}
		return subject + ".andThen(" + args[0] + ")", nil
	default:
		return "", fmt.Errorf("unsupported maybe method: %v", method.Kind)
	}
}

func (e *emitter) emitResultMethod(method *checker.ResultMethod) (string, error) {
	subject, err := e.emitExpr(method.Subject)
	if err != nil {
		return "", err
	}
	args, err := e.emitArgs(method.Args)
	if err != nil {
		return "", err
	}
	failArgs := func(name string, want int) error {
		return fmt.Errorf("result.%s expects %d arg(s)", name, want)
	}

	switch method.Kind {
	case checker.ResultExpect:
		if len(args) != 1 {
			return "", failArgs("expect", 1)
		}
		return subject + ".expect(" + args[0] + ")", nil
	case checker.ResultOr:
		if len(args) != 1 {
			return "", failArgs("or", 1)
		}
		return subject + ".or(" + args[0] + ")", nil
	case checker.ResultIsOk:
		return subject + ".isOk()", nil
	case checker.ResultIsErr:
		return subject + ".isErr()", nil
	case checker.ResultMap:
		if len(args) != 1 {
			return "", failArgs("map", 1)
		}
		return subject + ".map(" + args[0] + ")", nil
	case checker.ResultMapErr:
		if len(args) != 1 {
			return "", failArgs("map_err", 1)
		}
		return subject + ".mapErr(" + args[0] + ")", nil
	case checker.ResultAndThen:
		if len(args) != 1 {
			return "", failArgs("and_then", 1)
		}
		return subject + ".andThen(" + args[0] + ")", nil
	default:
		return "", fmt.Errorf("unsupported result method: %v", method.Kind)
	}
}

func (e *emitter) emitMutationExpr(subject string, lines []string, returnExpr string) (string, error) {
	child := &emitter{}
	child.line("(() => {")
	child.indent(func() {
		child.line("const __value = " + subject + ";")
		for _, line := range lines {
			child.line(line)
		}
		child.line("return " + returnExpr + ";")
	})
	child.line("})()")
	return strings.TrimSpace(child.builder.String()), nil
}

func (e *emitter) emitTemplateStr(expr *checker.TemplateStr) (string, error) {
	var out bytes.Buffer
	out.WriteByte('`')
	for _, chunk := range expr.Chunks {
		if literal, ok := chunk.(*checker.StrLiteral); ok {
			out.WriteString(escapeTemplateLiteral(literal.Value))
			continue
		}
		value, err := e.emitExpr(chunk)
		if err != nil {
			return "", err
		}
		out.WriteString("${")
		out.WriteString(value)
		out.WriteByte('}')
	}
	out.WriteByte('`')
	return out.String(), nil
}

func (e *emitter) emitInlineClosure(expr checker.Expression) (string, error) {
	child := &emitter{
		target:          e.target,
		moduleVars:      e.moduleVars,
		currentModule:   e.currentModule,
		currentFunction: e.currentFunction,
		currentReceiver: e.currentReceiver,
	}
	child.line("(() => {")
	child.indent(func() {
		var err error
		switch expr := expr.(type) {
		case *checker.If:
			err = child.emitIf(expr, true)
		case *checker.Block:
			err = child.emitBlock(expr, true)
		default:
			err = fmt.Errorf("unsupported inline closure expression %T", expr)
		}
		if err != nil {
			panic(err)
		}
	})
	child.line("})()")
	return strings.TrimSpace(child.builder.String()), nil
}

func (e *emitter) emitBinary(left checker.Expression, op string, right checker.Expression) (string, error) {
	leftValue, err := e.emitExpr(left)
	if err != nil {
		return "", err
	}
	rightValue, err := e.emitExpr(right)
	if err != nil {
		return "", err
	}
	return "(" + leftValue + " " + op + " " + rightValue + ")", nil
}

func (e *emitter) emitArgs(args []checker.Expression) ([]string, error) {
	out := make([]string, 0, len(args))
	for _, arg := range args {
		value, err := e.emitExpr(arg)
		if err != nil {
			return nil, err
		}
		out = append(out, value)
	}
	return out, nil
}

func (e *emitter) line(value string) {
	if value == "" {
		e.builder.WriteByte('\n')
		return
	}
	for i := 0; i < e.indentLevel; i++ {
		e.builder.WriteString("  ")
	}
	e.builder.WriteString(value)
	e.builder.WriteByte('\n')
}

func (e *emitter) indent(fn func()) {
	e.indentLevel++
	defer func() { e.indentLevel-- }()
	fn()
}

func (e *emitter) emitVariableName(name string) string {
	if e.currentReceiver != "" && name == e.currentReceiver {
		return "this"
	}
	return jsName(name)
}

func sortedStructInstanceFields(instance *checker.StructInstance) []string {
	if instance == nil {
		return nil
	}
	if structDef, ok := instance.StructType.(*checker.StructDef); ok && structDef != nil {
		return sortedFieldNames(structDef.Fields)
	}
	if len(instance.FieldTypes) > 0 {
		return sortedFieldNames(instance.FieldTypes)
	}
	fields := make([]string, 0, len(instance.Fields))
	for field := range instance.Fields {
		fields = append(fields, field)
	}
	sort.Strings(fields)
	return fields
}

func sortedFunctionNames(methods map[string]*checker.FunctionDef) []string {
	names := make([]string, 0, len(methods))
	for name := range methods {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedFieldNames(fields map[string]checker.Type) []string {
	names := make([]string, 0, len(fields))
	for name := range fields {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func moduleVarName(path string) string {
	replacer := strings.NewReplacer("/", "_", "-", "_", ".", "_")
	return "__module_" + replacer.Replace(path)
}

func jsName(name string) string {
	return name
}

func escapeTemplateLiteral(raw string) string {
	replacer := strings.NewReplacer("\\", "\\\\", "`", "\\`", "${", "\\${")
	return replacer.Replace(raw)
}
