// Code generated by ard; DO NOT EDIT.

package vm_next

import (
	"fmt"
	"github.com/akonwi/ard/air"
	stdlibffi "github.com/akonwi/ard/std_lib/ffi"
)

func init() {
	registerGeneratedHostExternAdapter(generatedStdlibHostExternAdapter)
}
func generatedStdlibHostExternAdapter(binding string, fn any) (hostExternDirect, bool) {
	switch binding {
	case "AsyncStart":
		typed, ok := fn.(func(stdlibffi.Callback0[struct{}]) stdlibffi.Fiber[struct{}])
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.Callback0[struct{}]](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "Base64Decode":
		typed, ok := fn.(func(string, stdlibffi.Maybe[bool]) (string, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[stdlibffi.Maybe[bool]](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0, out1 := typed(arg0, arg1)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "Base64DecodeURL":
		typed, ok := fn.(func(string, stdlibffi.Maybe[bool]) (string, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[stdlibffi.Maybe[bool]](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0, out1 := typed(arg0, arg1)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "Base64Encode":
		typed, ok := fn.(func(string, stdlibffi.Maybe[bool]) string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[stdlibffi.Maybe[bool]](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "Base64EncodeURL":
		typed, ok := fn.(func(string, stdlibffi.Maybe[bool]) string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[stdlibffi.Maybe[bool]](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "BoolToDynamic":
		typed, ok := fn.(func(bool) any)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[bool](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "CryptoHashPassword":
		typed, ok := fn.(func(string, stdlibffi.Maybe[int]) (string, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[stdlibffi.Maybe[int]](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0, out1 := typed(arg0, arg1)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "CryptoMd5":
		typed, ok := fn.(func(string) string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "CryptoScryptHash":
		typed, ok := fn.(func(string, stdlibffi.Maybe[string], stdlibffi.Maybe[int], stdlibffi.Maybe[int], stdlibffi.Maybe[int], stdlibffi.Maybe[int]) (string, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[stdlibffi.Maybe[string]](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg2, err := generatedHostArg[stdlibffi.Maybe[int]](vm, args[2])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 2: %w", binding, err)
			}
			arg3, err := generatedHostArg[stdlibffi.Maybe[int]](vm, args[3])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 3: %w", binding, err)
			}
			arg4, err := generatedHostArg[stdlibffi.Maybe[int]](vm, args[4])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 4: %w", binding, err)
			}
			arg5, err := generatedHostArg[stdlibffi.Maybe[int]](vm, args[5])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 5: %w", binding, err)
			}
			out0, out1 := typed(arg0, arg1, arg2, arg3, arg4, arg5)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "CryptoScryptVerify":
		typed, ok := fn.(func(string, string, stdlibffi.Maybe[int], stdlibffi.Maybe[int], stdlibffi.Maybe[int], stdlibffi.Maybe[int]) (bool, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg2, err := generatedHostArg[stdlibffi.Maybe[int]](vm, args[2])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 2: %w", binding, err)
			}
			arg3, err := generatedHostArg[stdlibffi.Maybe[int]](vm, args[3])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 3: %w", binding, err)
			}
			arg4, err := generatedHostArg[stdlibffi.Maybe[int]](vm, args[4])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 4: %w", binding, err)
			}
			arg5, err := generatedHostArg[stdlibffi.Maybe[int]](vm, args[5])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 5: %w", binding, err)
			}
			out0, out1 := typed(arg0, arg1, arg2, arg3, arg4, arg5)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "CryptoSha256":
		typed, ok := fn.(func(string) string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "CryptoSha512":
		typed, ok := fn.(func(string) string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "CryptoUUID":
		typed, ok := fn.(func() string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			out0 := typed()
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "CryptoVerifyPassword":
		typed, ok := fn.(func(string, string) (bool, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0, out1 := typed(arg0, arg1)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "DecodeBool":
		typed, ok := fn.(func(any) stdlibffi.Result[bool, stdlibffi.Error])
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnResult(vm, extern.Signature.Return, out0.Value, out0.Error, out0.Ok)
		}, true
	case "DecodeFloat":
		typed, ok := fn.(func(any) stdlibffi.Result[float64, stdlibffi.Error])
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnResult(vm, extern.Signature.Return, out0.Value, out0.Error, out0.Ok)
		}, true
	case "DecodeInt":
		typed, ok := fn.(func(any) stdlibffi.Result[int, stdlibffi.Error])
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnResult(vm, extern.Signature.Return, out0.Value, out0.Error, out0.Ok)
		}, true
	case "DecodeString":
		typed, ok := fn.(func(any) stdlibffi.Result[string, stdlibffi.Error])
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnResult(vm, extern.Signature.Return, out0.Value, out0.Error, out0.Ok)
		}, true
	case "DynamicToList":
		typed, ok := fn.(func(any) ([]any, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "DynamicToMap":
		typed, ok := fn.(func(any) (map[string]any, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "EnvGet":
		typed, ok := fn.(func(string) stdlibffi.Maybe[string])
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "ExtractField":
		typed, ok := fn.(func(any, string) (any, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0, out1 := typed(arg0, arg1)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "FS_Abs":
		typed, ok := fn.(func(string) (string, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "FS_AppendFile":
		typed, ok := fn.(func(string, string) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "FS_Copy":
		typed, ok := fn.(func(string, string) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "FS_CreateDir":
		typed, ok := fn.(func(string) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "FS_CreateFile":
		typed, ok := fn.(func(string) (bool, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "FS_Cwd":
		typed, ok := fn.(func() (string, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			out0, out1 := typed()
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "FS_DeleteDir":
		typed, ok := fn.(func(string) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "FS_DeleteFile":
		typed, ok := fn.(func(string) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "FS_Exists":
		typed, ok := fn.(func(string) bool)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "FS_IsDir":
		typed, ok := fn.(func(string) bool)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "FS_IsFile":
		typed, ok := fn.(func(string) bool)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "FS_ListDir":
		typed, ok := fn.(func(string) (map[string]bool, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "FS_ReadFile":
		typed, ok := fn.(func(string) (string, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "FS_Rename":
		typed, ok := fn.(func(string, string) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "FS_WriteFile":
		typed, ok := fn.(func(string, string) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "FloatFloor":
		typed, ok := fn.(func(float64) float64)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[float64](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "FloatFromInt":
		typed, ok := fn.(func(int) float64)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[int](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "FloatFromStr":
		typed, ok := fn.(func(string) stdlibffi.Maybe[float64])
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "FloatToDynamic":
		typed, ok := fn.(func(float64) any)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[float64](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "GetPathValue":
		typed, ok := fn.(func(stdlibffi.RawRequest, string) string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.RawRequest](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "GetQueryParam":
		typed, ok := fn.(func(stdlibffi.RawRequest, string) string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.RawRequest](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "GetReqPath":
		typed, ok := fn.(func(stdlibffi.RawRequest) string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.RawRequest](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "GetTodayString":
		typed, ok := fn.(func() string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			out0 := typed()
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "HTTP_Do":
		typed, ok := fn.(func(string, string, any, map[string]string, stdlibffi.Maybe[int]) (stdlibffi.RawResponse, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg2, err := generatedHostArg[any](vm, args[2])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 2: %w", binding, err)
			}
			arg3, err := generatedHostArg[map[string]string](vm, args[3])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 3: %w", binding, err)
			}
			arg4, err := generatedHostArg[stdlibffi.Maybe[int]](vm, args[4])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 4: %w", binding, err)
			}
			out0, out1 := typed(arg0, arg1, arg2, arg3, arg4)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "HTTP_ResponseBody":
		typed, ok := fn.(func(stdlibffi.RawResponse) (string, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.RawResponse](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "HTTP_ResponseClose":
		typed, ok := fn.(func(stdlibffi.RawResponse))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.RawResponse](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			typed(arg0)
			return generatedHostReturnVoid(vm, extern.Signature.Return)
		}, true
	case "HTTP_ResponseHeaders":
		typed, ok := fn.(func(stdlibffi.RawResponse) map[string]string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.RawResponse](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "HTTP_ResponseStatus":
		typed, ok := fn.(func(stdlibffi.RawResponse) int)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.RawResponse](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "HTTP_Serve":
		typed, ok := fn.(func(int, map[string]stdlibffi.Callback2[stdlibffi.Request, *stdlibffi.Response, struct{}]) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[int](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[map[string]stdlibffi.Callback2[stdlibffi.Request, *stdlibffi.Response, struct{}]](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			out0 := typed(arg0, arg1)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "HexDecode":
		typed, ok := fn.(func(string) (string, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "HexEncode":
		typed, ok := fn.(func(string) string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "IntFromStr":
		typed, ok := fn.(func(string) stdlibffi.Maybe[int])
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "IntToDynamic":
		typed, ok := fn.(func(int) any)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[int](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "IsNil":
		typed, ok := fn.(func(any) bool)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "JsonEncode":
		typed, ok := fn.(func(any) (string, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "JsonToDynamic":
		typed, ok := fn.(func(string) (any, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "ListToDynamic":
		typed, ok := fn.(func([]any) any)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[[]any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "MapToDynamic":
		typed, ok := fn.(func(map[string]any) any)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[map[string]any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "Now":
		typed, ok := fn.(func() int)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			out0 := typed()
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "OsArgs":
		typed, ok := fn.(func() []string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			out0 := typed()
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "Print":
		typed, ok := fn.(func(string))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			typed(arg0)
			return generatedHostReturnVoid(vm, extern.Signature.Return)
		}, true
	case "ReadLine":
		typed, ok := fn.(func() (string, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			out0, out1 := typed()
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "Sleep":
		typed, ok := fn.(func(int))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[int](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			typed(arg0)
			return generatedHostReturnVoid(vm, extern.Signature.Return)
		}, true
	case "SqlBeginTx":
		typed, ok := fn.(func(stdlibffi.Db) (stdlibffi.Tx, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.Db](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "SqlClose":
		typed, ok := fn.(func(stdlibffi.Db) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.Db](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "SqlCommit":
		typed, ok := fn.(func(stdlibffi.Tx) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.Tx](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "SqlCreateConnection":
		typed, ok := fn.(func(string) (stdlibffi.Db, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0, out1 := typed(arg0)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "SqlExecute":
		typed, ok := fn.(func(any, string, []any) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg2, err := generatedHostArg[[]any](vm, args[2])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 2: %w", binding, err)
			}
			out0 := typed(arg0, arg1, arg2)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "SqlExtractParams":
		typed, ok := fn.(func(string) []string)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "SqlQuery":
		typed, ok := fn.(func(any, string, []any) ([]any, error))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[any](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			arg1, err := generatedHostArg[string](vm, args[1])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 1: %w", binding, err)
			}
			arg2, err := generatedHostArg[[]any](vm, args[2])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 2: %w", binding, err)
			}
			out0, out1 := typed(arg0, arg1, arg2)
			return generatedHostReturnValueError(vm, extern.Signature.Return, out0, out1)
		}, true
	case "SqlRollback":
		typed, ok := fn.(func(stdlibffi.Tx) error)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.Tx](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnError(vm, extern.Signature.Return, out0)
		}, true
	case "StrToDynamic":
		typed, ok := fn.(func(string) any)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[string](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			out0 := typed(arg0)
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "VoidToDynamic":
		typed, ok := fn.(func() any)
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			out0 := typed()
			return generatedHostReturnValue(vm, extern.Signature.Return, out0)
		}, true
	case "WaitFor":
		typed, ok := fn.(func(stdlibffi.WaitGroup))
		if !ok {
			return nil, false
		}
		return func(vm *VM, extern air.Extern, binding string, args []Value) (Value, error) {
			arg0, err := generatedHostArg[stdlibffi.WaitGroup](vm, args[0])
			if err != nil {
				return Value{}, fmt.Errorf("extern %s arg 0: %w", binding, err)
			}
			typed(arg0)
			return generatedHostReturnVoid(vm, extern.Signature.Return)
		}, true
	}
	return nil, false
}
